(() => {
const $=s=>document.querySelector(s),canvas=$('#space'),ctx=canvas.getContext('2d'),game=new MeteorPatrol(),keys={left:false,right:false};let running=false,paused=false,last=0,best=0,time=0,oldScore=0,oldHealth=3;
try{best=Math.max(0,Number(localStorage.getItem('meteor-patrol-best'))||0)}catch{}$('#best').textContent=String(best).padStart(4,'0');
function record(){if(game.score<=best)return;best=game.score;$('#best').textContent=String(best).padStart(4,'0');try{localStorage.setItem('meteor-patrol-best',best);$('#best-note').textContent='Your best flight so far. Keep exploring.'}catch{$('#best-note').textContent='Record kept for this visit. Storage unavailable.'}}
function hud(){const left=game.target-game.spawned+game.meteors.length;$('#score').textContent=String(game.score).padStart(4,'0');$('#health').textContent='◆ '.repeat(Math.max(0,game.health))+'◇ '.repeat(3-Math.max(0,game.health));$('#health').setAttribute('aria-label',game.health+' hull points');$('#wave').textContent='0'+(game.wave+1);$('#wave-name').textContent=['A quiet corner of the cosmos','Through the drifting belt','The final frontier'][game.wave];$('#remaining').textContent=left+' meteors to clear';$('#progress').style.width=(1-left/game.target)*100+'%';$('#shield-state').textContent=game.shield>0?'SHIELD ACTIVE · '+Math.ceil(game.shield)+'s':game.cooldown>0?'RECHARGING · '+Math.ceil(game.cooldown)+'s':'SHIELD READY';$('#shield').disabled=!running||paused||game.cooldown>0;$('#shield').textContent=game.shield>0?'◇ PROTECTED':game.cooldown>0?'◇ '+Math.ceil(game.cooldown)+'s':'◇ SHIELD'}
function show(title,copy,button,tag){$('#title').textContent=title;$('#copy').textContent=copy;$('#start').textContent=button;$('#tag').textContent=tag;$('#overlay').hidden=false;keys.left=keys.right=false;$('#announce').textContent=title+' '+copy}
function start(){if(paused)paused=false;else if(game.status==='complete')game.load(game.wave+1);else game.reset();running=true;oldScore=game.score;oldHealth=game.health;last=performance.now();$('#overlay').hidden=true;$('#pause').disabled=false;$('#pause').setAttribute('aria-label','Pause mission');canvas.focus({preventScroll:true});if($('.game').getBoundingClientRect().bottom>innerHeight)$('.game').scrollIntoView({block:'start',behavior:'instant'});hud()}
function pause(){if(!running||paused)return;paused=true;show('Holding your orbit.','Your mission can wait a moment.','Back to the mission →','PAUSED');$('#pause').setAttribute('aria-label','Resume mission');hud()}
$('#start').onclick=start;$('#pause').onclick=()=>paused?start():pause();function protect(){if(running&&!paused&&game.protect()){$('#announce').textContent='Shield activated for three seconds.';hud()}}$('#shield').onclick=protect;
for(const direction of ['left','right']){const b=$('#'+direction);b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);if(running&&!paused)keys[direction]=true};for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>keys[direction]=false)}
function aim(e){if(!running||paused)return;const r=canvas.getBoundingClientRect();game.move((e.clientX-r.left)/r.width*600)}canvas.onpointermove=aim;canvas.onpointerdown=e=>{e.preventDefault();canvas.setPointerCapture(e.pointerId);aim(e);canvas.focus({preventScroll:true})};
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.target.closest('input,textarea,select'))return;if(['KeyP','Escape'].includes(e.code)&&!e.repeat){paused?start():pause();return}if(!running||paused)return;if(['ArrowLeft','ArrowRight','KeyA','KeyD','Space'].includes(e.code)){if(e.code==='Space'&&e.target.closest('button,a'))return;e.preventDefault();if(e.code==='Space'){if(!e.repeat)protect()}else keys[['ArrowLeft','KeyA'].includes(e.code)?'left':'right']=true}});document.addEventListener('keyup',e=>{if(['ArrowLeft','KeyA'].includes(e.code))keys.left=false;if(['ArrowRight','KeyD'].includes(e.code))keys.right=false});window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});
function draw(){const sky=ctx.createLinearGradient(0,0,0,700);sky.addColorStop(0,'#0a1b2b');sky.addColorStop(1,'#14343e');ctx.fillStyle=sky;ctx.fillRect(0,0,600,700);for(let i=0;i<75;i++){const x=(i*137.3)%600,y=(i*83.7+time*(i%3+1)*9)%700;ctx.fillStyle=i%4===0?'#c0e5df99':'#93bdc744';ctx.beginPath();ctx.arc(x,y,i%4===0?1.4:.8,0,Math.PI*2);ctx.fill()}ctx.strokeStyle='#8ccfc014';for(let i=0;i<4;i++){ctx.beginPath();ctx.ellipse(300,760,200+i*110,90+i*48,0,0,Math.PI*2);ctx.stroke()}ctx.fillStyle='#397a7833';ctx.beginPath();ctx.ellipse(300,740,440,90,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#9edcce';ctx.shadowColor='#87e0ce';ctx.shadowBlur=10;for(const b of game.shots)ctx.fillRect(b.x-2,b.y-10,4,15);ctx.shadowBlur=0;
for(const m of game.meteors){ctx.save();ctx.translate(m.x,m.y);ctx.rotate(m.spin);ctx.fillStyle=m.hp>1?'#a68373':'#8f9b9a';ctx.strokeStyle=m.hp>1?'#d5aa8e':'#bfcebf';ctx.lineWidth=2;ctx.beginPath();for(let i=0;i<9;i++){const a=i/9*Math.PI*2,r=m.r*(i%2?.9:1.04);ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r)}ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#243b4055';ctx.beginPath();ctx.arc(-m.r*.25,-m.r*.22,m.r*.27,0,Math.PI*2);ctx.arc(m.r*.35,m.r*.29,m.r*.18,0,Math.PI*2);ctx.fill();if(m.hp>1){ctx.strokeStyle='#f5cd9c';ctx.beginPath();ctx.arc(0,0,m.r*.64,0,Math.PI*2);ctx.stroke()}ctx.restore()}
const p=game.ship;ctx.save();ctx.translate(p.x,p.y);if(game.invulnerable>0&&Math.floor(game.invulnerable*10)%2)ctx.globalAlpha=.45;if(running&&!paused){ctx.fillStyle='#eec595';ctx.beginPath();ctx.moveTo(-8,20);ctx.lineTo(0,39+Math.sin(time*30)*9);ctx.lineTo(8,20);ctx.fill()}ctx.fillStyle='#8fe0d3';ctx.beginPath();ctx.moveTo(0,-29);ctx.lineTo(24,22);ctx.lineTo(0,12);ctx.lineTo(-24,22);ctx.closePath();ctx.fill();ctx.fillStyle='#285562';ctx.beginPath();ctx.moveTo(0,-16);ctx.lineTo(7,3);ctx.lineTo(-7,3);ctx.closePath();ctx.fill();ctx.strokeStyle='#dbfff0';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-27);ctx.lineTo(0,10);ctx.stroke();if(game.shield>0){ctx.strokeStyle='#adf9e1';ctx.fillStyle='#80ebdc19';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,43,0,Math.PI*2);ctx.fill();ctx.stroke()}ctx.restore()}
function frame(now){const dt=Math.min(.04,(now-last)/1000||0);last=now;if(running&&!paused){time+=dt;game.step(dt,keys);if(game.score>oldScore){oldScore=game.score;record()}if(game.health<oldHealth){oldHealth=game.health;$('#announce').textContent=game.health+' hull points remaining.'}hud();if(game.status!=='playing'){running=false;$('#pause').disabled=true;record();if(game.status==='complete')show('A clear stretch of sky.',`Wave ${game.wave+1} complete. ${game.score} points. Ready for the next?`,'Next wave →','MISSION CHECKPOINT');else if(game.status==='won')show('The cosmos says thank you.',`All three waves cleared! Final score: ${game.score}.`,'Fly again →','MISSION ACCOMPLISHED');else show('Another flight awaits.',`Your mission scored ${game.score} points. Every flight teaches you something.`,'Try again →','BACK TO BASE');hud()}}draw();requestAnimationFrame(frame)}hud();requestAnimationFrame(frame);
})();
