(()=>{
 const $=id=>document.getElementById(id);for(let n=2;n<=12;n++)$('table').add(new Option(`${n} times table`,String(n)));
 let q,round=0,stars=0,first=true,active=false,paused=false,resolved=false,time=12,last=performance.now(),table,pace,operation;
 const key=()=>`sprout-math-best:${$('operation').value}:${$('table').value}:${$('pace').value}`;
 function best(){try{$('best').textContent=`Best: ${localStorage.getItem(key())||'—'} / 10`}catch{$('best').textContent='Best: —'}}
 function controls(){$('operation').disabled=active;$('table').disabled=active;$('pace').disabled=active;$('pause').disabled=!active||resolved;$('pause').textContent=paused?'Resume':'Pause';document.querySelector('.world').classList.toggle('paused',paused);document.querySelectorAll('.answer').forEach(b=>b.disabled=!active||paused||resolved)}
 function beginQuestion(){q=MultiplyRun.question(table,Math.random,operation);first=true;resolved=false;paused=false;time=12;$('round').textContent=`Question ${round+1} / 10`;$('question').textContent=`${q.a} ${q.symbol} ${q.b} = ?`;$('instruction').textContent='Which gate has the answer?';$('message').textContent='Find your answer gate';$('explanation').textContent=operation==='multiply'?`Think of ${q.b} groups of ${q.a}.`:'Take a moment to work it out.';$('next').classList.add('hidden');$('answers').replaceChildren();q.options.forEach((n,i)=>{const b=document.createElement('button');b.className='answer';b.innerHTML=`${n}<small>KEY ${i+1}</small>`;b.setAttribute('aria-label',`Answer ${n}`);b.onclick=()=>answer(i);$('answers').append(b)});controls();renderTimer()}
 function renderTimer(){$('timer').textContent=paused?'Paused':pace==='sprint'&&!resolved?`${Math.ceil(time)} seconds`:'Take your time. Every step counts.'}
 function reveal(){resolved=true;$('explanation').textContent=MultiplyRun.explanation(q);$('next').textContent=round===9?'See my results →':'Next question →';$('next').classList.remove('hidden');document.querySelectorAll('.answer').forEach((b,i)=>{if(q.options[i]===q.answer)b.classList.add('correct')});controls();$('next').focus();renderTimer()}
 function answer(i){if(!active||paused||resolved)return;const correct=q.options[i]===q.answer;document.querySelector('.runner').style.left=`calc(${(i+.5)*100/3}% - 20px)`;if(correct){if(first)stars++;$('stars').textContent=`★ ${stars} first tries`;$('message').textContent=first?'Great thinking!':'You worked it out!';reveal()}else{first=false;document.querySelectorAll('.answer')[i].classList.add('wrong');$('message').textContent='Keep going — try another gate.';$('explanation').textContent=MultiplyRun.explanation(q);time=12;renderTimer()}}
 $('start').onclick=()=>{operation=$('operation').value;table=$('table').value;pace=$('pace').value;active=true;round=0;stars=0;$('stars').textContent='★ 0 first tries';$('start').textContent='Restart run';document.querySelector('.world').classList.add('running');last=performance.now();beginQuestion()};
 $('next').onclick=()=>{if(!active||!resolved)return;round++;if(round<10){beginQuestion();document.querySelector('.answer').focus();return}active=false;document.querySelector('.world').classList.remove('running');$('next').classList.add('hidden');$('question').textContent=`${stars} / 10 ★`;$('instruction').textContent='Run complete!';$('message').textContent='Ten questions. Stronger maths skills.';$('explanation').textContent='Try again, or choose a different kind of maths. Every practice run helps.';$('start').textContent='Run again →';try{localStorage.setItem(key(),String(Math.max(stars,Number(localStorage.getItem(key()))||0)))}catch{}controls();best();$('start').focus()};
 function pause(){if(!active||resolved)return;paused=!paused;controls();renderTimer();last=performance.now()}
 $('pause').onclick=pause;document.addEventListener('visibilitychange',()=>{if(document.hidden&&active&&!paused&&!resolved)pause()});
 document.addEventListener('keydown',e=>{if(e.repeat||['SELECT','INPUT'].includes(e.target.tagName))return;if(['1','2','3'].includes(e.key)){e.preventDefault();answer(Number(e.key)-1)}});
 $('operation').onchange=()=>{$('table-label').textContent=['multiply','divide'].includes($('operation').value)?'Times table':'Number to practise';best()};$('table').onchange=best;$('pace').onchange=best;best();
 function tick(now){const dt=Math.min((now-last)/1000,.25);last=now;if(active&&!paused&&!resolved&&pace==='sprint'){time-=dt;if(time<=0){first=false;$('message').textContent='Let’s learn this one together.';reveal()}else renderTimer()}requestAnimationFrame(tick)}requestAnimationFrame(tick);
})();
