(()=>{
 const $=id=>document.getElementById(id);for(let n=2;n<=12;n++)$('table').add(new Option(`${n} times table`,String(n)));
 let q,round=0,stars=0,first=true,active=false,paused=false,resolved=false,time=12,last=performance.now(),table,pace,operation,travelling=false,coins=0;

 const islandNames={add:'Addition Woods',subtract:'Subtraction Peaks',multiply:'Multiplication Meadow',divide:'Division Valley'};
 function completed(){try{const value=JSON.parse(localStorage.getItem('sprout-math-islands')||'{}');return value&&typeof value==='object'&&!Array.isArray(value)?value:{}}catch{return {}}}
 function saveMap(){try{const data=completed();data[operation]=Math.max(Number(data[operation])||0,stars);localStorage.setItem('sprout-math-islands',JSON.stringify(data))}catch{}}
 function paintMap(){const data=completed();document.querySelectorAll('[data-island]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.island===$('operation').value));const label=islandNames[b.dataset.island];b.querySelector('b').textContent=label+(Object.hasOwn(data,b.dataset.island)?' ✓':'')});$('map-progress').textContent=active?`${islandNames[operation]} · stop ${Math.min(round+1,10)} of 10`:`${Object.keys(data).filter(k=>k in islandNames).length} / 4 islands explored`;$('checkpoints').replaceChildren();for(let i=0;i<10;i++){const dot=document.createElement('span');dot.textContent=i<round?'✓':i+1;dot.className=i<round?'done':i===round&&active?'current':'';dot.setAttribute('aria-label',`Checkpoint ${i+1}${i<round?' completed':''}`);$('checkpoints').append(dot)}}
 function startTrail(){travelling=true;resolved=false;paused=false;$('next').classList.add('hidden');document.querySelector('.world').classList.remove('at-gate');$('round').textContent=`Checkpoint ${round+1} / 10`;$('message').textContent='Follow the trail!';$('explanation').textContent='Jump over logs with Space, ↑, or the Jump button. The runner stops at each maths gate.';$('trail-note').textContent='Next stop: a maths challenge';paintMap();controls();$('landscape').focus({preventScroll:true});MathTrail.begin(operation,round,beginQuestion,()=>{coins++;$('coins').textContent=`● ${coins}`})}
 $('jump').onclick=()=>MathTrail.hop();document.querySelector('#landscape').addEventListener('pointerdown',()=>{if(active&&!paused)MathTrail.hop()});
 document.querySelectorAll('[data-island]').forEach(b=>b.onclick=()=>{if(active)return;$('operation').value=b.dataset.island;$('operation').dispatchEvent(new Event('change'))});

 const key=()=>`sprout-math-best:${$('operation').value}:${$('table').value}:${$('pace').value}`;
 function best(){try{$('best').textContent=`Best: ${localStorage.getItem(key())||'—'} / 10`}catch{$('best').textContent='Best: —'}}
 function controls(){document.querySelectorAll('[data-island]').forEach(b=>b.disabled=active);$('jump').disabled=!active||!travelling||paused;$('operation').disabled=active;$('table').disabled=active;$('pace').disabled=active;$('pause').disabled=!active||resolved;$('pause').textContent=paused?'Resume':'Pause';document.querySelector('.world').classList.toggle('paused',paused);document.querySelectorAll('.answer').forEach(b=>b.disabled=!active||paused||resolved||travelling)}
 function beginQuestion(){document.querySelector('.world').classList.add('at-gate');travelling=false;$('trail-note').textContent='Checkpoint reached — choose the answer';q=MultiplyRun.question(table,Math.random,operation);first=true;resolved=false;paused=false;time=12;$('round').textContent=`Question ${round+1} / 10`;$('question').textContent=`${q.a} ${q.symbol} ${q.b} = ?`;$('instruction').textContent='Which gate has the answer?';$('message').textContent='Find your answer gate';$('explanation').textContent=operation==='multiply'?`Think of ${q.b} groups of ${q.a}.`:'Take a moment to work it out.';$('next').classList.add('hidden');$('answers').replaceChildren();q.options.forEach((n,i)=>{const b=document.createElement('button');b.className='answer';b.innerHTML=`${n}<small>KEY ${i+1}</small>`;b.setAttribute('aria-label',`Answer ${n}`);b.onclick=()=>answer(i);$('answers').append(b)});controls();renderTimer();document.querySelector('.answer').focus({preventScroll:true})}
 function renderTimer(){$('timer').textContent=paused?'Paused':pace==='sprint'&&!resolved?`${Math.ceil(time)} seconds`:'Take your time. Every step counts.'}
 function reveal(){resolved=true;$('explanation').textContent=MultiplyRun.explanation(q);$('next').textContent=round===9?'See my results →':'Next question →';$('next').classList.remove('hidden');document.querySelectorAll('.answer').forEach((b,i)=>{if(q.options[i]===q.answer)b.classList.add('correct')});controls();$('next').focus();renderTimer()}
 function answer(i){if(!active||paused||resolved||travelling)return;const correct=q.options[i]===q.answer;if(correct){if(first)stars++;$('stars').textContent=`★ ${stars} first tries`;$('message').textContent=first?'Great thinking!':'You worked it out!';reveal()}else{first=false;document.querySelectorAll('.answer')[i].classList.add('wrong');$('message').textContent='Keep going — try another gate.';$('explanation').textContent=MultiplyRun.explanation(q);time=12;renderTimer()}}
 $('start').onclick=()=>{operation=$('operation').value;table=$('table').value;pace=$('pace').value;active=true;round=0;stars=0;$('stars').textContent='★ 0 first tries';$('start').textContent='Restart run';coins=0;$('coins').textContent='● 0';document.querySelector('.world').classList.add('running');last=performance.now();startTrail();document.querySelector('.world').scrollIntoView({block:'center',behavior:'instant'})};
 $('next').onclick=()=>{if(!active||!resolved)return;round++;if(round<10){startTrail();return}active=false;MathTrail.stop();saveMap();paintMap();document.querySelector('.world').classList.remove('running');$('next').classList.add('hidden');$('question').textContent=`${stars} / 10 ★`;$('instruction').textContent='Run complete!';$('message').textContent='Ten questions. Stronger maths skills.';$('explanation').textContent='Try again, or choose a different kind of maths. Every practice run helps.';$('start').textContent='Run again →';try{localStorage.setItem(key(),String(Math.max(stars,Number(localStorage.getItem(key()))||0)))}catch{}controls();best();$('start').focus()};
 function pause(){if(!active||resolved)return;paused=!paused;MathTrail.setPaused(paused);controls();renderTimer();last=performance.now()}
 $('pause').onclick=pause;document.addEventListener('visibilitychange',()=>{if(document.hidden&&active&&!paused&&!resolved)pause()});
 document.addEventListener('keydown',e=>{if(e.repeat||['SELECT','INPUT'].includes(e.target.tagName))return;if((e.code==='Space'||e.key==='ArrowUp')&&travelling&&active&&!paused&&e.target.tagName!=='BUTTON'){e.preventDefault();MathTrail.hop()}if(['1','2','3'].includes(e.key)){e.preventDefault();answer(Number(e.key)-1)}});
 $('operation').onchange=()=>{paintMap();$('table-label').textContent=['multiply','divide'].includes($('operation').value)?'Times table':'Number to practise';best()};$('table').onchange=best;$('pace').onchange=best;best();paintMap();
 function tick(now){const dt=Math.min((now-last)/1000,.25);last=now;if(active&&!paused&&!resolved&&!travelling&&pace==='sprint'){time-=dt;if(time<=0){first=false;$('message').textContent='Let’s learn this one together.';reveal()}else renderTimer()}requestAnimationFrame(tick)}requestAnimationFrame(tick);
})();
