(()=>{
 const $=id=>document.getElementById(id),{levels,initial,step}=RobotRoutes,labels={F:'↑',L:'↶',R:'↷'};
 let levelIndex=0,state,program=[],cursor=0,running=false,timer=null;
 function records(){try{const data=JSON.parse(localStorage.getItem('sprout-robot-routes')||'[]');return Array.isArray(data)?data.filter(x=>Number.isInteger(x)&&x>=0&&x<levels.length):[]}catch{return []}}
 function stop(){clearTimeout(timer);timer=null;running=false}
 function nav(){const complete=records();$('levels').replaceChildren();levels.forEach((l,i)=>{const b=document.createElement('button');b.textContent=`${i+1}${complete.includes(i)?' ✓':''}`;b.setAttribute('aria-label',`Mission ${i+1}: ${l.name}${complete.includes(i)?', complete':''}`);b.setAttribute('aria-pressed',String(i===levelIndex));b.dataset.level=i;b.onclick=()=>load(i);$('levels').append(b)})}
 function load(i){stop();levelIndex=i;program=[];reset();nav();$('title').textContent=`${i+1}. ${levels[i].name}`}
 function reset(){stop();state=initial(levels[levelIndex]);cursor=0;$('message').textContent='Plan a route to the goal.';$('hint').textContent=levels[levelIndex].hint;$('next').classList.add('hidden');draw()}
 function draw(){const level=levels[levelIndex];$('grid').style.gridTemplateColumns=`repeat(${level.map[0].length},1fr)`;$('grid').replaceChildren();level.map.forEach((row,y)=>[...row].forEach((ch,x)=>{const cell=document.createElement('div');cell.className='cell'+(ch==='#'?' wall':ch==='G'?' goal':ch==='*'&&!state.collected.includes(`${x},${y}`)?' star':'');let name=ch==='#'?'wall':ch==='G'?'goal':ch==='*'&&!state.collected.includes(`${x},${y}`)?'star':'path';cell.textContent=name==='goal'?'G':name==='star'?'★':'';if(state.x===x&&state.y===y){cell.innerHTML=`<span class="robot">🤖</span><span class="arrow">${['↑','→','↓','←'][state.d]}</span>`;name=`robot facing ${['north','east','south','west'][state.d]}`}cell.setAttribute('aria-label',`Row ${y+1}, column ${x+1}: ${name}`);$('grid').append(cell)}));$('stars').textContent=`★ ${state.collected.length} / ${state.stars.length} collected`;$('facing').textContent=`Robot facing ${['north ↑','east →','south ↓','west ←'][state.d]}`;$('program').replaceChildren();program.forEach((c,i)=>{const b=document.createElement('button');b.className='command'+(i<cursor?' done':i===cursor?' current':'');b.textContent=`${i+1} ${labels[c]}`;b.setAttribute('aria-label',`Remove command ${i+1}: ${c==='F'?'forward':c==='L'?'turn left':'turn right'}`);b.disabled=running;b.onclick=()=>{program.splice(i,1);reset()};$('program').append(b)});document.querySelectorAll('[data-command]').forEach(b=>b.disabled=running||program.length>=60);$('double').disabled=running||!program.length||program.length>30;$('undo').disabled=$('clear').disabled=running||!program.length;$('run').disabled=running||!program.length;$('step').disabled=running||cursor>=program.length||state.won||!!state.error}
 function advance(){if(cursor>=program.length||state.won||state.error)return;state=step(levels[levelIndex],state,program[cursor]);cursor++;if(state.error){stop();$('message').textContent='Time to debug!';$('hint').textContent=`Command ${cursor}: ${state.error}`}else if(state.won){stop();$('message').textContent='Mission complete!';$('hint').textContent='Your instructions collected every star and reached the goal.';try{localStorage.setItem('sprout-robot-routes',JSON.stringify([...new Set([...records(),levelIndex])]))}catch{}nav();$('next').textContent=levelIndex===levels.length-1?'Play the first mission again →':'Next mission →';$('next').classList.remove('hidden')}else if(cursor===program.length){stop();$('message').textContent='Your program has finished.';$('hint').textContent=state.x===state.goal.x&&state.y===state.goal.y?'You reached the goal, but still need to collect every star. Add a detour!':'Add more commands to reach the goal. Editing starts the robot again.'}else{$('message').textContent=`Running command ${cursor} of ${program.length}`;$('hint').textContent=levels[levelIndex].hint}draw()}
 function tick(){if(!running)return;if(document.hidden){stop();$('message').textContent='Run paused while you were away.';$('hint').textContent='Use Step once to continue, or Run program to restart.';draw();return}advance();if(running)timer=setTimeout(tick,450)}
 document.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>{if(running||program.length>=60)return;program.push(b.dataset.command);reset()});$('undo').onclick=()=>{program.pop();reset()};$('clear').onclick=()=>{program=[];reset()};$('double').onclick=()=>{if(program.length&&program.length<=30){program=[...program,...program];reset()}};$('reset').onclick=reset;$('step').onclick=advance;$('run').onclick=()=>{reset();running=true;draw();tick()};$('next').onclick=()=>load((levelIndex+1)%levels.length);load(0);
})();
