(() => {
const $=s=>document.querySelector(s),canvas=$('#canvas'),ctx=canvas.getContext('2d'),game=new PrismBreak.Game(),keys={left:false,right:false},colors=['#f79288','#f7bd86','#f3d985','#88cfc1','#8abbe5','#a69bdd','#d39ec9'];let running=false,paused=false,last=0,best=0,sound=false,audio,trail=[];
try{best=Math.max(0,Number(localStorage.getItem('prism-break-best'))||0)}catch{}$('#best').textContent=String(best).padStart(4,'0');
function beep(f){if(!sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=f;g.gain.setValueAtTime(.025,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.09);o.start();o.stop(audio.currentTime+.09)}catch{}}
$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent=sound?'Sound on':'Sound off';$('#sound').setAttribute('aria-pressed',sound);beep(500)};
function record(){if(game.score<=best)return;best=game.score;$('#best').textContent=String(best).padStart(4,'0');try{localStorage.setItem('prism-break-best',best);$('#record-note').textContent='Your brightest run yet.'}catch{$('#record-note').textContent='Best for this visit. Storage unavailable.'}}
function hud(){const remaining=game.bricks.filter(b=>b.hp>0).length;$('#score').textContent=String(game.score).padStart(4,'0');$('#level').textContent=`0${game.level+1} / 03`;$('#lives').textContent='● '.repeat(game.lives)+'○ '.repeat(3-game.lives);$('#lives').setAttribute('aria-label',game.lives+' lives');$('#remaining').textContent=remaining;$('#fill').style.width=(1-remaining/game.bricks.length)*100+'%';$('#level-name').textContent=['01 · First spectrum','02 · Missing pieces','03 · Twice as bright'][game.level];$('#power-state').textContent=game.wide>0?`WIDE PADDLE · ${Math.ceil(game.wide)}s LEFT`:'READY WHEN YOU ARE';$('#status').textContent=game.status==='ready'?'TAP THE BOARD OR PRESS SPACE TO LAUNCH.':'KEEP IT BOUNCING. KEEP IT BRIGHT.'}
function show(title,copy,button,tag){$('#title').textContent=title;$('#copy').textContent=copy;$('#start').textContent=button;$('#tag').textContent=tag;$('#overlay').hidden=false;keys.left=keys.right=false;$('#announce').textContent=title+' '+copy}
function start(){if(paused)paused=false;else if(game.status==='complete')game.load(game.level+1);else game.reset();running=true;last=performance.now();trail=[];$('#overlay').hidden=true;$('#pause').disabled=false;$('#pause').setAttribute('aria-label','Pause game');canvas.focus({preventScroll:true});hud()}
function pause(){if(!running||paused)return;paused=true;show('A quick color break.','Your ball is right where you left it.','Back to the bounce →','PAUSED');$('#pause').setAttribute('aria-label','Resume game')}
$('#start').onclick=start;$('#pause').onclick=()=>paused?start():pause();
function aim(e){if(!running||paused)return;const rect=canvas.getBoundingClientRect();game.move((e.clientX-rect.left)/rect.width*720)}canvas.onpointermove=aim;canvas.onpointerdown=e=>{e.preventDefault();aim(e);if(running&&!paused)game.launch();canvas.setPointerCapture(e.pointerId);canvas.focus({preventScroll:true})};
document.addEventListener('keydown',e=>{if(e.altKey||e.ctrlKey||e.metaKey||e.target.closest('input,textarea,select'))return;if(['KeyP','Escape'].includes(e.code)&&!e.repeat){paused?start():pause();return}if(!running||paused)return;if(['ArrowLeft','KeyA','ArrowRight','KeyD','Space'].includes(e.code)){if(e.code==='Space'&&e.target.closest('button,a'))return;e.preventDefault();if(e.code==='Space')game.launch();else keys[['ArrowLeft','KeyA'].includes(e.code)?'left':'right']=true}});document.addEventListener('keyup',e=>{if(['ArrowLeft','KeyA'].includes(e.code))keys.left=false;if(['ArrowRight','KeyD'].includes(e.code))keys.right=false});window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});
function rr(x,y,w,h,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function draw(){ctx.fillStyle='#101d34';ctx.fillRect(0,0,720,640);ctx.fillStyle='#ffffff09';for(let x=24;x<720;x+=28)for(let y=12;y<640;y+=28){ctx.beginPath();ctx.arc(x,y,1,0,Math.PI*2);ctx.fill()}ctx.strokeStyle='#ffffff0b';ctx.strokeRect(15,20,690,600);for(const b of game.bricks){if(!b.hp)continue;rr(b.x,b.y+3,b.w,b.h,5,'#0004');rr(b.x,b.y,b.w,b.h,5,colors[b.row]);rr(b.x+4,b.y+3,b.w-8,3,2,'#ffffff35');if(b.hp===2){ctx.strokeStyle='#ffffff77';for(let i=8;i<b.w;i+=13){ctx.beginPath();ctx.moveTo(b.x+i,b.y+7);ctx.lineTo(b.x+i-6,b.y+17);ctx.stroke()}}}for(const d of game.drops){rr(d.x-15,d.y-10,30,20,8,'#ffda89');ctx.fillStyle='#735838';ctx.font='bold 21px Arial';ctx.textAlign='center';ctx.fillText('↔',d.x,d.y+6)}for(let i=0;i<trail.length;i++){ctx.fillStyle=`rgba(172,210,255,${i/trail.length*.25})`;ctx.beginPath();ctx.arc(trail[i].x,trail[i].y,i/trail.length*7,0,Math.PI*2);ctx.fill()}const p=game.paddle;ctx.shadowBlur=22;ctx.shadowColor=game.wide>0?'#ffcf83':'#91beff';rr(p.x-p.w/2,578,p.w,13,7,game.wide>0?'#ffcf83':'#bddaff');ctx.shadowBlur=0;rr(p.x-p.w/2+8,581,p.w-16,3,2,'#ffffff88');ctx.fillStyle='#fff5df';ctx.beginPath();ctx.arc(game.ball.x,game.ball.y,8,0,Math.PI*2);ctx.fill();if(game.status==='ready'){ctx.fillStyle='#8192ad';ctx.textAlign='center';ctx.font='11px Arial';ctx.fillText('TAP OR PRESS SPACE',360,520)}}
function frame(now){const dt=Math.min(.04,(now-last)/1000||0);last=now;if(running&&!paused){game.move(game.paddle.x+((keys.right?1:0)-(keys.left?1:0))*500*dt);const score=game.score,lives=game.lives;game.step(dt);if(game.score>score){beep(550+game.level*100);record()}if(game.lives<lives){beep(120);trail=[];$('#announce').textContent=game.lives+' lives remaining. Tap to launch again.'}if(game.status==='playing'){trail.push({x:game.ball.x,y:game.ball.y});if(trail.length>13)trail.shift()}hud();if(['complete','won','over'].includes(game.status)){running=false;$('#pause').disabled=true;record();if(game.status==='complete')show('Another shade of brilliant.',`Level ${game.level+1} cleared. ${game.score} points and counting.`,'Next level →','COLLECTION COMPLETE');else if(game.status==='won')show('Every color. All yours.',`All three levels cleared with ${game.score} points!`,'Play again →','YOU BROKE THE SPECTRUM');else show('One more bounce?',`You scored ${game.score} points. A fresh start is a tap away.`,'Try again →','BACK TO THE BEGINNING')}}draw();requestAnimationFrame(frame)}hud();requestAnimationFrame(frame);
})();
