(()=>{
const $=id=>document.getElementById(id),{courses,fold,shuffle}=LanguageGarden,{languages,date}=LanguageCatalogue,byId=new Map(languages.map(l=>[l.id,l]));
let language=null,limit=48,session=null;
function read(){try{const d=JSON.parse(localStorage.getItem('sprout-language-garden')||'{}');return d&&typeof d==='object'&&!Array.isArray(d)?d:{}}catch{return {}}}
let data=read();data.saved=Array.isArray(data.saved)?data.saved.filter(id=>byId.has(id)):[];data.custom=data.custom&&typeof data.custom==='object'&&!Array.isArray(data.custom)?data.custom:{};data.progress=data.progress&&typeof data.progress==='object'&&!Array.isArray(data.progress)?data.progress:{};
function persist(){try{localStorage.setItem('sprout-language-garden',JSON.stringify(data));$('storage-status').textContent='';return true}catch{$('storage-status').textContent='This browser could not save your changes. You can keep practising, but this session may not be remembered.';return false}}
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e}
function custom(id){const rows=data.custom[id];return Array.isArray(rows)?rows.filter(c=>c&&typeof c.text==='string'&&typeof c.meaning==='string'&&typeof c.note==='string'&&c.text.length<=100&&c.meaning.length<=100&&c.note.length<=200).slice(0,100):[]}
function cards(id){return [...(courses[id]?.cards||[]),...custom(id).map(c=>({...c,custom:true}))]}
function cancelSpeech(){window.speechSynthesis?.cancel()}
function renderCatalogue(){const entered=fold($('search').value),query=entered==='ypruba'?'yoruba':entered,filter=$('filter').value;let rows=languages.filter(l=>(!query||fold([l.id,...l.names,courses[l.id]?.native||''].join(' ')).includes(query))&&(filter!=='courses'||!!courses[l.id])&&(filter!=='saved'||data.saved.includes(l.id)||custom(l.id).length));rows.sort((a,b)=>Number(!!courses[b.id])-Number(!!courses[a.id])||a.name.localeCompare(b.name));$('languages').replaceChildren();for(const l of rows.slice(0,limit)){const ready=!!courses[l.id],own=custom(l.id).length,b=el('button',undefined,'language'+(ready?' ready':''));b.dataset.language=l.id;b.append(el('small',`${l.id.toUpperCase()}${l.scope==='macrolanguage'?' · Language group':''}`),el('b',l.name));if(ready)b.append(el('span',courses[l.id].native,'native'));b.append(el('span',ready?`${courses[l.id].cards.length} starter words · Begin →`:own?`${own} of your word cards →`:'No starter lessons yet · Explore →','status'));b.onclick=()=>openLanguage(l.id);$('languages').append(b)}$('result-count').textContent=rows.length?`Showing ${Math.min(limit,rows.length)} of ${rows.length.toLocaleString()} matching entries`:'No matching entry. Try an English name, alternate name, or language code.';$('more').classList.toggle('hidden',limit>=rows.length);$('saved-count').textContent=new Set(data.saved).size}
function voice(){if(!language||!window.speechSynthesis)return null;const tag=courses[language.id]?.locale||language.id;return speechSynthesis.getVoices().find(v=>v.localService&&v.lang.toLowerCase()===tag.toLowerCase())||speechSynthesis.getVoices().find(v=>v.localService&&v.lang.toLowerCase().split('-')[0]===tag.toLowerCase().split('-')[0])||null}
function voiceStatus(){const available=voice();$('speak').disabled=!available||!session||session.done;$('voice-status').textContent=available?'On-device voice available. Listen and repeat aloud at your own pace.':'No matching on-device voice is available here. Text practice still works.'}
function progress(){const p=data.progress[language.id];$('progress').textContent=p&&Number.isFinite(p.correct)&&Number.isFinite(p.total)?`Last meaning practice: ${p.correct} / ${p.total} correct.`:'Start a practice round to grow your progress.'}
function renderWords(){const query=fold($('phrase-search').value),rows=cards(language.id).filter(c=>fold(c.text+' '+c.meaning).includes(query));$('word-list').replaceChildren();rows.forEach(c=>{const row=el('div',undefined,'word-row'),body=el('div'),term=el('strong',c.text);term.dir=courses[language.id]?.dir||'auto';term.lang=courses[language.id]?.locale||language.id;body.append(term,el('p',c.meaning),el('p',c.note),el('small',c.custom?'Your word card':c.topic+' · Starter sample'));row.append(body);if(c.custom){const remove=el('button','Remove');remove.setAttribute('aria-label','Remove your card: '+c.meaning);remove.onclick=()=>{data.custom[language.id]=custom(language.id).filter(x=>x.text!==c.text);persist();closeStudy();renderWords()};row.append(remove)}$('word-list').append(row)});$('empty').textContent=rows.length?'':cards(language.id).length?'No word cards match your search.':'No lessons have been added for this language yet. You can add your own word cards below.';const count=cards(language.id).length;$('flash').disabled=count===0;$('tutor-start').disabled=count===0;$('quiz').disabled=new Set(cards(language.id).map(c=>c.meaning)).size<2}
function openLanguage(id){SproutTutor.close();cancelSpeech();language=byId.get(id);session=null;$('study').classList.add('hidden');$('browse').classList.add('hidden');$('detail').classList.remove('hidden');$('language-code').textContent=`${language.id.toUpperCase()}${language.scope==='macrolanguage'?' · LANGUAGE GROUP':''}`;$('language-name').textContent=language.name;$('native-name').textContent=courses[id]?.native||'';$('bookmark').textContent=data.saved.includes(id)?'Saved language ♥':'Save language ♡';$('bookmark').setAttribute('aria-pressed',String(data.saved.includes(id)));$('availability').textContent=courses[id]?`Starter course: ${courses[id].cards.length} word cards covering ${[...new Set(courses[id].cards.map(c=>c.topic))].join(", ").toLowerCase()}, with meaning practice.${courses[id].variety?' Variety: '+courses[id].variety+'.':''} More lessons are still to come.`:'Catalogue entry — no starter course is available yet. Add your own word cards to practise this language. Two different meanings are needed for a quiz.';$('phrase-search').value='';$('form-status').textContent='';$('add-word').reset();renderWords();progress();window.scrollTo({top:0});}
function closeStudy(){cancelSpeech();session=null;$('study').classList.add('hidden')}
function begin(mode){SproutTutor.close();cancelSpeech();const deck=shuffle(cards(language.id));if(!deck.length)return;session={mode,deck,index:0,correct:0,answered:false,done:false};$('study').classList.remove('hidden');showCard();$('study').scrollIntoView({block:'start'})}
function showCard(){session.answered=false;const c=session.deck[session.index];$('study-count').textContent=`${session.index+1} / ${session.deck.length}`;$('study-type').textContent=`${session.mode==='flash'?'WORD CARD':'WHAT DOES THIS MEAN?'} · ${c.topic||'Your words'}`;$('study-word').textContent=c.text;$('study-word').lang=courses[language.id]?.locale||language.id;$('study-word').dir=courses[language.id]?.dir||'auto';$('choices').replaceChildren();$('study-message').textContent=session.mode==='flash'?'Say the word aloud, then reveal its meaning.':'Choose the meaning in English.';$('study-note').textContent='';$('reveal').classList.toggle('hidden',session.mode!=='flash');$('study-next').disabled=session.mode==='quiz';$('study-next').textContent=session.index===session.deck.length-1?'Finish practice →':'Next word →';if(session.mode==='quiz'){const validMeanings=new Set(session.deck.filter(x=>fold(x.text)===fold(c.text)).map(x=>x.meaning));const alternatives=shuffle([...new Set(session.deck.map(x=>x.meaning))].filter(x=>!validMeanings.has(x))).slice(0,2);shuffle([c.meaning,...alternatives]).forEach(meaning=>{const b=el('button',meaning,'choice');b.onclick=()=>answer(meaning,b);$('choices').append(b)})}voiceStatus()}
function answer(meaning,button){if(!session||session.answered||session.done)return;session.answered=true;const c=session.deck[session.index],correct=meaning===c.meaning;if(correct)session.correct++;document.querySelectorAll('.choice').forEach(b=>{b.disabled=true;if(b.textContent===c.meaning)b.classList.add('correct')});if(!correct)button.classList.add('wrong');$('study-message').textContent=correct?'You remembered it!':`The meaning is: ${c.meaning}`;$('study-note').textContent=c.note;$('study-next').disabled=false}
$('study-next').onclick=()=>{cancelSpeech();if(!session)return;if(session.done){closeStudy();return}if(session.mode==='quiz'&&!session.answered)return;session.index++;if(session.index<session.deck.length){showCard();return}session.done=true;$('study-word').textContent='Practice complete!';$('study-word').dir='ltr';$('study-word').lang='en';$('choices').replaceChildren();$('reveal').classList.add('hidden');$('study-message').textContent=session.mode==='quiz'?`${session.correct} of ${session.deck.length} meanings remembered.`:`You explored ${session.deck.length} word cards.`;$('study-note').textContent='Come back for another little practice whenever you like.';$('study-next').textContent='Close practice';if(session.mode==='quiz'){data.progress[language.id]={correct:session.correct,total:session.deck.length};persist();progress()}voiceStatus()};
$('reveal').onclick=()=>{if(!session||session.done)return;const c=session.deck[session.index];$('study-message').textContent=c.meaning;$('study-note').textContent=c.note;$('reveal').classList.add('hidden')};$('speak').onclick=()=>{if(!session||session.done)return;const v=voice();if(!v)return;cancelSpeech();const u=new SpeechSynthesisUtterance(session.deck[session.index].text);u.voice=v;u.lang=v.lang;u.rate=.8;u.onerror=()=>{$('voice-status').textContent='The device voice could not play. You can keep practising with text.'};speechSynthesis.speak(u)};
$('add-word').onsubmit=e=>{e.preventDefault();const text=$('custom-text').value.trim(),meaning=$('custom-meaning').value.trim(),note=$('custom-note').value.trim();if(!text||!meaning){$('form-status').textContent='Enter both a word and its meaning.';return}if(custom(language.id).length>=100){$('form-status').textContent='This language already has 100 custom cards. Remove a card before adding another.';return}if(cards(language.id).some(c=>fold(c.text)===fold(text)||fold(c.meaning)===fold(meaning))){$('form-status').textContent='This word or meaning already has a card.';return}data.custom[language.id]=[...custom(language.id),{text,meaning,note}];const ok=persist();$('form-status').textContent=ok?'Word card saved.':'Word card added for this session; browser storage is unavailable.';$('add-word').reset();closeStudy();renderWords()};
document.querySelectorAll('[data-open-language]').forEach(button=>{const id=button.dataset.openLanguage;button.textContent=`${courses[id].native} · ${courses[id].cards.length} words`;button.onclick=()=>openLanguage(id)});
$('tutor-start').onclick=()=>{closeStudy();SproutTutor.open({id:language.id,name:language.name,cards:cards(language.id),locale:courses[language.id]?.locale||language.id,dir:courses[language.id]?.dir||'auto'});};
$('bookmark').onclick=()=>{const id=language.id;data.saved=data.saved.includes(id)?data.saved.filter(x=>x!==id):[...data.saved,id];persist();$('bookmark').textContent=data.saved.includes(id)?'Saved language ♥':'Save language ♡';$('bookmark').setAttribute('aria-pressed',String(data.saved.includes(id)))};$('back').onclick=()=>{SproutTutor.close();closeStudy();$('detail').classList.add('hidden');$('browse').classList.remove('hidden');renderCatalogue()};$('flash').onclick=()=>begin('flash');$('quiz').onclick=()=>begin('quiz');$('close-study').onclick=closeStudy;$('phrase-search').oninput=renderWords;$('search').oninput=$('filter').onchange=()=>{limit=48;renderCatalogue()};$('more').onclick=()=>{limit+=48;renderCatalogue()};window.speechSynthesis?.addEventListener('voiceschanged',()=>{if(session)voiceStatus()});document.addEventListener('visibilitychange',()=>{if(document.hidden)cancelSpeech()});$('catalogue-count').textContent=languages.length.toLocaleString();$('registry-date').textContent=date;$('course-count').textContent=Object.keys(courses).length;$('word-count').textContent=Object.values(courses).reduce((n,c)=>n+c.cards.length,0);renderCatalogue();
})();
