(() => {
 const $=s=>document.querySelector(s),{MemoryGame,randomSeed}=LittleMatches;
 const collections={garden:[['🌷','Tulip'],['🌻','Sunflower'],['🍄','Mushroom'],['🦋','Butterfly'],['🐝','Bee'],['🍓','Strawberry'],['🍀','Clover'],['🐞','Ladybird'],['🌈','Rainbow'],['🐌','Snail'],['🌸','Blossom'],['🍋','Lemon']],space:[['🚀','Rocket'],['🌙','Moon'],['⭐','Star'],['🪐','Planet'],['👽','Alien'],['🛰️','Satellite'],['☄️','Comet'],['🛸','Flying saucer'],['🌍','Earth'],['☀️','Sun'],['🔭','Telescope'],['👨‍🚀','Astronaut']],treats:[['🍦','Ice cream'],['🍩','Doughnut'],['🧁','Cupcake'],['🍪','Cookie'],['🍭','Lollipop'],['🍉','Watermelon'],['🍒','Cherries'],['🍰','Cake'],['🥨','Pretzel'],['🥞','Pancakes'],['🍫','Chocolate'],['🍑','Peach']]};
 let game,theme='garden',daily=false,day='',started=false,paused=false,peeking=false,elapsed=0,last=0,pending=null,records={},storageOK=true;
 try{const saved=JSON.parse(localStorage.getItem('little-matches-records')||'{}');if(saved&&typeof saved==='object'&&!Array.isArray(saved))records=saved}catch{storageOK=false}
 const dateKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
 const key=()=>daily?'daily:'+day:'normal:'+theme+':'+game.pairs;
 const clock=ms=>{const s=Math.floor(ms/1000);return Math.floor(s/60)+':'+String(s%60).padStart(2,'0')};
 function record(){const r=records[key()];const valid=r&&Number.isFinite(r.moves)&&Number.isFinite(r.time);$('#best').textContent=valid?r.moves+' moves':'—';$('#best-note').textContent=valid?`${clock(r.time)} · ${daily?'This daily board':game.pairs+' pairs · '+theme}${storageOK?'':' · this visit only'}`:storageOK?'Your first finished board starts the story.':'Records can only be kept for this visit.'}
 function tick(){const now=performance.now();if(started&&!paused&&!game.won)elapsed+=now-last;last=now;$('#time').textContent=clock(elapsed)}
 function clear(){clearTimeout(pending);pending=null}
 function hud(){$('#pairs').innerHTML=game.found+' <small>/ '+game.pairs+'</small>';$('#moves').textContent=game.moves;$('#time').textContent=clock(elapsed);$('#peek').disabled=paused||peeking||game.won||game.open.length>0;$('#pause').disabled=game.won;$('#pause').textContent=paused?'▶':'Ⅱ';$('#pause').setAttribute('aria-label',paused?'Resume game':'Pause game')}
 function render(){for(const [i,card] of [...$('#board').children].entries()){const data=game.cards[i],visible=data.matched||game.open.includes(i)||peeking;card.classList.toggle('revealed',visible);card.classList.toggle('matched',data.matched);card.disabled=data.matched||paused||peeking||game.open.includes(i)||game.open.length===2||game.won;card.setAttribute('aria-label',data.matched?`${collections[theme][data.value][1]}, matched`:visible?collections[theme][data.value][1]:`Card ${i+1}, face down`)}$('#board').inert=paused||game.won;$('#board').style.visibility=paused?'hidden':'visible';hud()}
 function cover(title,copy,button,tag){$('#cover-title').textContent=title;$('#cover-copy').textContent=copy;$('#continue').textContent=button;$('#cover-tag').textContent=tag;$('#cover').hidden=false}
 function resolve(){clear();game.close();peeking=false;render()}
 function schedule(){clear();pending=setTimeout(()=>{resolve();$('#message').textContent='A new turn. What do you remember?'},peeking?1600:850)}
 function win(){started=false;const old=records[key()];if(!old||game.moves<old.moves||game.moves===old.moves&&elapsed<old.time){records[key()]={moves:game.moves,time:Math.floor(elapsed)};const dailyKeys=Object.keys(records).filter(k=>k.startsWith('daily:')).sort();for(const k of dailyKeys.slice(0,-31))delete records[k];try{localStorage.setItem('little-matches-records',JSON.stringify(records))}catch{storageOK=false}}record();cover('Every pair, found.',`${game.pairs} pairs in ${game.moves} moves and ${clock(elapsed)}. ${game.moves===game.pairs?'A perfect board!':'A lovely little achievement.'}`,'One more board →','LOOK AT YOU GO');$('#message').textContent=`Board complete! ${game.moves} moves in ${clock(elapsed)}.`;render()}
 function flip(i){if(paused||peeking)return;tick();const result=game.flip(i);if(result==='ignored')return;if(!started){started=true;last=performance.now()}render();if(result==='first')$('#message').textContent='Now, where is its partner?';if(result==='miss'){ $('#message').textContent='Not quite. Remember those two!';schedule()}if(result==='match')$('#message').textContent='A lovely match! Keep going.';if(result==='won')win()}
 function start(isDaily=false){clear();daily=isDaily;day=dateKey();if(daily){theme='garden';$('#difficulty').value='8'}game=new MemoryGame(Number($('#difficulty').value),daily?randomSeed(day+':little-matches-v1'):Math.random);started=false;paused=false;peeking=false;elapsed=0;last=performance.now();$('#cover').hidden=true;$('#board').replaceChildren();for(const [i,c]of game.cards.entries()){const b=document.createElement('button');b.className='card';b.dataset.index=i;b.innerHTML=`<span class="back-symbol" aria-hidden="true">✿</span><span class="face" aria-hidden="true">${collections[theme][c.value][0]}</span><span class="card-number" aria-hidden="true">${String(i+1).padStart(2,'0')}</span>`;b.onclick=()=>flip(i);$('#board').append(b)}for(const b of $('#themes').children)b.setAttribute('aria-pressed',b.dataset.theme===theme);$('#message').textContent=daily?'Today’s board is ready. Make your first match.':'Turn over any two cards to begin.';$('#daily-date').textContent=new Date().toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});render();record()}
 function togglePause(){if(game.won)return;tick();paused=!paused;if(paused){clear();cover('A little breather.','Your cards will be waiting.','Keep matching →','TAKE YOUR TIME')}else{$('#cover').hidden=true;last=performance.now();if(peeking||game.open.length===2)schedule()}render()}
 $('#pause').onclick=togglePause;$('#continue').onclick=()=>game.won?start(daily):togglePause();$('#new-game').onclick=()=>start(false);$('#daily').onclick=()=>start(true);$('#difficulty').onchange=()=>start(false);for(const b of $('#themes').children)b.onclick=()=>{theme=b.dataset.theme;start(false)};
 $('#peek').onclick=()=>{if(paused||peeking||game.won||game.open.length)return;tick();started=true;game.moves+=2;peeking=true;$('#message').textContent='A quick peek! Two moves added.';render();schedule()};
 $('#board').addEventListener('keydown',e=>{const dirs={ArrowLeft:-1,ArrowRight:1,ArrowUp:-4,ArrowDown:4};if(!(e.key in dirs))return;e.preventDefault();const cards=[...$('#board').children],from=cards.indexOf(document.activeElement);if(from<0)return;let i=from;for(let n=0;n<cards.length;n++){i=(i+dirs[e.key]+cards.length)%cards.length;if(!cards[i].disabled){cards[i].focus();break}}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&started&&!paused&&!game.won)togglePause()});start();setInterval(tick,200);
})();
