(() => {
  const $=s=>document.querySelector(s),categories={questions:'♟ Question',ideas:'✧ Idea or tip',celebrations:'★ Little win'};
  if(location.hostname.endsWith('.github.io')){const message=$('#connection-message');message.hidden=false;message.textContent='Shared community posts need a game server and are not available on this public edition. You can still play, study and train using the menu.';document.querySelectorAll('main button,main input,main select,#open-moderation').forEach(el=>el.disabled=true);$('#feed-empty').hidden=false;$('#empty-title').textContent='Community is not connected';$('#empty-description').textContent='No shared posts are loaded on this edition.';return}
  let session={token:null,name:null},page=1,pages=1,category='all',requestNumber=0,searchTimer,toastTimer,afterProfile=null,thread=null,deleteTarget=null,reportTarget=null,busy=false;
  try{const saved=JSON.parse(localStorage.getItem('chess-club-community'));if(saved&&typeof saved.token==='string'&&/^[a-f0-9]{48}$/.test(saved.token))session=saved}catch{}
  function node(tag,className,text){const el=document.createElement(tag);if(className)el.className=className;if(text!==undefined)el.textContent=text;return el}
  function button(text,action,className=''){const b=node('button',className,text);b.type='button';b.onclick=action;return b}
  function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4000)}
  function remember(){try{localStorage.setItem('chess-club-community',JSON.stringify(session))}catch{toast('Your nickname works in this tab, but this browser could not save it for next time.')}}
  async function api(route,body,moderator=false){const headers={...(session.token?{Authorization:'Bearer '+session.token}:{}),...(body===undefined?{}:{'Content-Type':'application/json'}),...(moderator?{'X-Community-Moderator':$('#moderator-key').value}:{})};const response=await fetch('/api/community'+route,{method:body===undefined?'GET':'POST',headers,...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(10000)});let result;try{result=await response.json()}catch{throw Error('The community server is unavailable. Please try again.')}if(!response.ok){if(response.status===401){session={token:null,name:null};remember();renderProfile()}throw Error(result.error||'The request could not be completed.')}return result}
  function renderProfile(){$('#profile-name').textContent=session.name?'Hi, '+session.name+'.':'Hello, chess friend.';$('#profile-description').textContent=session.name?'Your next good idea belongs here.':'Choose a nickname when you’re ready to join in.';$('#edit-profile').textContent=session.name?'Change nickname':'Choose a nickname'}
  function needProfile(action){if(session.token&&session.name){action();return}afterProfile=action;$('#nickname').value=session.name||'';$('#profile-error').textContent='';$('#profile-dialog').showModal();$('#nickname').focus()}
  document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());
  $('#edit-profile').onclick=()=>{afterProfile=null;$('#nickname').value=session.name||'';$('#profile-error').textContent='';$('#profile-dialog').showModal()};
  $('#profile-dialog').addEventListener('close',()=>{afterProfile=null});
  $('#profile-form').onsubmit=async e=>{e.preventDefault();const submit=$('#save-profile');submit.disabled=true;$('#profile-error').textContent='';try{const result=await api('/session',{name:$('#nickname').value});session={token:result.token||session.token,name:result.name};remember();renderProfile();const action=afterProfile;afterProfile=null;$('#profile-dialog').close();await loadPosts();action?.()}catch(error){$('#profile-error').textContent=error.message}finally{submit.disabled=false}};
  function date(value){return new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(value))}
  function connectionError(message){$('#connection-message').hidden=false;$('#connection-message').textContent=message}
  async function loadPosts(){if(location.protocol==='file:'){connectionError('Community needs the game server. Open http://localhost:8001 after starting the website.');$('#feed-count').textContent='Server connection needed';return}const ticket=++requestNumber;try{const q=new URLSearchParams({page:String(page),category,q:$('#search-posts').value,sort:$('#sort-posts').value});const data=await api('/posts?'+q);if(ticket!==requestNumber)return;pages=data.pages;if(page>pages){page=pages;return loadPosts()}$('#connection-message').hidden=true;$('#posts').innerHTML='';for(const post of data.posts)renderPost(post);$('#feed-count').textContent=data.total+' '+(data.total===1?'conversation':'conversations');$('#total-posts').textContent=data.stats.posts;$('#total-replies').textContent=data.stats.replies;$('#feed-empty').hidden=data.posts.length>0;const filtered=data.stats.posts>0||category!=='all'||$('#search-posts').value||$('#sort-posts').value==='mine';$('#empty-title').textContent=filtered?'No conversations here yet.':'Every club starts with hello.';$('#empty-description').textContent=filtered?'Try another category or search, or start your own conversation.':'Be the first to ask a chess question or share something you’ve learned.';$('#empty-new-post').textContent=filtered?'Start a conversation':'Start the first conversation';$('#prev-page').disabled=page<=1;$('#next-page').disabled=page>=pages;$('#page-label').textContent=`Page ${page} of ${pages}`}catch(error){if(ticket===requestNumber){connectionError(error.message);$('#feed-count').textContent='Could not load conversations';}}}
  function likeButton(post){const b=button((post.liked?'♥':'♡')+' '+post.likes,()=>needProfile(async()=>{b.disabled=true;try{const updated=await api('/posts/'+post.id+'/like',{liked:!post.liked});if(thread?.id===post.id)renderThread(updated);await loadPosts()}catch(error){toast(error.message)}finally{b.disabled=false}}),post.liked?'liked':'');b.setAttribute('aria-label',(post.liked?'Unlike':'Like')+' this post');b.setAttribute('aria-pressed',post.liked);return b}
  function renderPost(post){const card=node('article','post-card'),top=node('div','post-topline');top.append(node('span','post-tag',categories[post.category]),node('span','post-meta',post.name+' · '+date(post.createdAt)));const title=button(post.title,()=>openThread(post.id),'post-title');const preview=node('p','post-preview',post.text.length>220?post.text.slice(0,220)+'…':post.text);const actions=node('div','post-footer');actions.append(likeButton(post),button('↳ '+post.replyCount+' '+(post.replyCount===1?'reply':'replies'),()=>openThread(post.id)));if(post.own)actions.append(node('span','post-owner','Your post'));card.append(top,title,preview,actions);$('#posts').append(card)}
  function compose(preset){needProfile(()=>{if(preset){$('#post-category').value=preset.category;$('#post-title').value=preset.title;$('#post-text').value=''}$('#compose-error').textContent='';$('#compose-dialog').showModal();$('#post-title').focus()})}
  $('#new-post').onclick=$('#empty-new-post').onclick=()=>compose();
  document.querySelectorAll('[data-starter]').forEach(b=>b.onclick=()=>compose({category:b.dataset.starter,title:{questions:'How do I know when to castle?',ideas:'One chess tip that helped me…',celebrations:'My latest little chess win!'}[b.dataset.starter]}));
  $('#compose-form').onsubmit=e=>{e.preventDefault();needProfile(async()=>{if(busy)return;busy=true;$('#publish-post').disabled=true;$('#compose-error').textContent='';try{const post=await api('/posts',{category:$('#post-category').value,title:$('#post-title').value,text:$('#post-text').value});$('#compose-dialog').close();$('#post-title').value='';$('#post-text').value='';page=1;await loadPosts();await openThread(post.id);toast('Your conversation is on the board.')}catch(error){$('#compose-error').textContent=error.message}finally{busy=false;$('#publish-post').disabled=false}})};
  async function openThread(id){try{const post=await api('/posts/'+id);$('#reply-text').value='';$('#reply-error').textContent='';renderThread(post);if(!$('#thread-dialog').open)$('#thread-dialog').showModal();history.replaceState(null,'','#post='+id)}catch(error){toast(error.message)}}
  $('#thread-dialog').addEventListener('close',()=>{thread=null;history.replaceState(null,'',location.pathname+location.search)});
  function renderThread(post){thread=post;$('#thread-category').textContent=categories[post.category];$('#thread-title').textContent=post.title;$('#thread-author').textContent=post.name+' · '+date(post.createdAt);$('#thread-text').textContent=post.text;$('#thread-actions').innerHTML='';$('#thread-actions').append(likeButton(post),button('Copy link',async()=>{const link=new URL(location.href);link.hash='post='+post.id;try{await navigator.clipboard.writeText(link.href);toast('Conversation link copied.')}catch{toast('Copy the link from your browser’s address bar.')}}),button('Report',()=>needProfile(()=>{reportTarget=post.id;$('#report-error').textContent='';$('#report-dialog').showModal()})));if(post.own)$('#thread-actions').append(button('Delete my post',()=>confirmDelete(post.id)));
    $('#reply-heading').textContent=post.replyCount+' '+(post.replyCount===1?'reply':'replies');$('#replies').innerHTML='';if(!post.replies.length)$('#replies').append(node('p','subtle','Be the first to share a helpful thought.'));for(const reply of post.replies){const el=node('article','reply'),top=node('div','reply-top');top.append(node('strong','',reply.name),node('span','post-meta',date(reply.createdAt)));el.append(top,node('p','',reply.text));if(reply.own)el.append(button('Delete my reply',()=>confirmDelete(post.id,reply.id),'text-button'));$('#replies').append(el)}
  }
  $('#reply-form').onsubmit=e=>{e.preventDefault();const content=$('#reply-text').value,id=thread?.id;if(!id)return;needProfile(async()=>{if(busy)return;busy=true;$('#send-reply').disabled=true;$('#reply-error').textContent='';try{const post=await api('/posts/'+id+'/reply',{text:content});if(thread?.id===id){renderThread(post);$('#reply-text').value=''}loadPosts();toast('Reply added.')}catch(error){$('#reply-error').textContent=error.message}finally{busy=false;$('#send-reply').disabled=false}})};
  function confirmDelete(postId,replyId=null){deleteTarget={postId,replyId};$('#delete-detail').textContent=replyId?'Your reply will be permanently removed.':'Deleting a post also removes its replies. This cannot be undone.';$('#delete-error').textContent='';$('#delete-dialog').showModal()}
  $('#confirm-delete').onclick=async()=>{if(!deleteTarget)return;const target=deleteTarget;$('#confirm-delete').disabled=true;try{const result=await api('/posts/'+target.postId+'/delete'+(target.replyId?'/'+target.replyId:''),{});$('#delete-dialog').close();if(target.replyId&&thread?.id===target.postId)renderThread(result);else if(thread?.id===target.postId)$('#thread-dialog').close();deleteTarget=null;await loadPosts();toast('Message deleted.')}catch(error){$('#delete-error').textContent=error.message}finally{$('#confirm-delete').disabled=false}};
  $('#report-form').onsubmit=async e=>{e.preventDefault();if(!reportTarget)return;$('#submit-report').disabled=true;try{await api('/posts/'+reportTarget+'/report',{reason:$('#report-reason').value});$('#report-dialog').close();if(thread?.id===reportTarget)$('#thread-dialog').close();reportTarget=null;await loadPosts();toast('Conversation hidden for the site owner to review.')}catch(error){$('#report-error').textContent=error.message}finally{$('#submit-report').disabled=false}};
  document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{category=b.dataset.category;page=1;document.querySelectorAll('[data-category]').forEach(x=>x.classList.toggle('active',x===b));loadPosts()});$('#sort-posts').onchange=()=>{page=1;loadPosts()};$('#search-posts').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{page=1;loadPosts()},250)};$('#refresh-posts').onclick=loadPosts;$('#prev-page').onclick=()=>{page=Math.max(1,page-1);loadPosts()};$('#next-page').onclick=()=>{page=Math.min(pages,page+1);loadPosts()};
  $('#open-moderation').onclick=()=>{$('#moderator-error').textContent='';$('#moderation-posts').innerHTML='';$('#moderation-dialog').showModal()};$('#moderation-dialog').addEventListener('close',()=>{$('#moderator-key').value='';$('#moderation-posts').innerHTML=''});
  async function loadModeration(){const result=await api('/moderation',undefined,true);$('#moderator-error').textContent='';$('#moderation-posts').innerHTML='';if(!result.posts.length)$('#moderation-posts').append(node('p','subtle','No reported conversations to review.'));for(const post of result.posts){const card=node('article','moderation-card');card.append(node('h3','',post.title),node('p','post-meta',post.name),node('div','post-body',post.text));for(const reply of post.replies)card.append(node('p','post-body',reply.name+': '+reply.text));for(const report of post.reports)card.append(node('p','report-reason','Report: '+report.reason));const actions=node('div','button-row');for(const [action,label]of [['restore','Restore conversation'],['remove','Remove permanently']])actions.append(button(label,async()=>{try{await api('/moderation',{id:post.id,action},true);await loadModeration();await loadPosts()}catch(error){$('#moderator-error').textContent=error.message}}));card.append(actions);$('#moderation-posts').append(card)}}
  $('#moderator-form').onsubmit=async e=>{e.preventDefault();try{await loadModeration()}catch(error){$('#moderator-error').textContent=error.message}};
  renderProfile();loadPosts();if(session.token&&location.protocol!=='file:')api('/me').then(result=>{if(!result.name){session={token:null,name:null};remember()}else session.name=result.name;renderProfile()}).catch(()=>{});
  if(/^#post=[a-f0-9]{16}$/.test(location.hash))openThread(location.hash.slice(6));
  setInterval(()=>{if(!document.hidden&&!document.querySelector('dialog[open]'))loadPosts()},30000);
})();
