(()=>{
 const $=id=>document.getElementById(id),{gardens,shuffle,tiles,hint}=WordGarden;
 let garden,deck=[],index=0,letters=[],selected=[],solved=false,helped=false,stars=0,tricky=[],review=false;
 function records(){try{const data=JSON.parse(localStorage.getItem('sprout-word-gardens')||'{}');return data&&typeof data==='object'&&!Array.isArray(data)?data:{}}catch{return {}}}
 function map(){const data=records();$('gardens').replaceChildren();$('progress').textContent=`${gardens.filter(g=>data[g.id]?.complete).length} / 4 gardens grown`;gardens.forEach((g,i)=>{const b=document.createElement('button');b.className='garden';b.dataset.garden=g.id;b.disabled=i>0&&!data[gardens[i-1].id]?.complete;b.innerHTML=`<span aria-hidden="true">${g.icon}</span><b>${g.name}</b><p>${g.description}</p><small>${b.disabled?'Finish the previous garden to unlock':data[g.id]?.complete?`✓ Grown · best ${Number(data[g.id].best)||0} / 6 stars`:'6 words · Start planting →'}</small>`;b.onclick=()=>start(g);$('gardens').append(b)});$('map').classList.remove('hidden');$('play').classList.add('hidden');$('results').classList.add('hidden')}
 function start(g,words){garden=g;review=!!words;deck=shuffle(words||g.words);index=0;stars=0;tricky=[];$('map').classList.add('hidden');$('play').classList.remove('hidden');$('results').classList.add('hidden');show();$('play').scrollIntoView({block:'start'})}
 function show(){letters=tiles(deck[index][0]);selected=[];solved=false;helped=false;$('picture').textContent=deck[index][1];$('clue').textContent=deck[index][2];$('sentence').textContent=deck[index][3];$('step').textContent=`Word ${index+1} / ${deck.length}`;$('flowers').replaceChildren();deck.forEach((_,i)=>{const s=document.createElement('span');s.textContent=i<index?'🌻':i===index?'🌱':'·';s.setAttribute('aria-label',`Word ${i+1}${i<index?' completed':''}`);$('flowers').append(s)});$('message').textContent='Build the word from these letters.';$('explanation').textContent='Every letter tile is used once. You can move letters back if you change your mind.';$('next').classList.add('hidden');draw()}
 function draw(){$('slots').classList.toggle('solved',solved);$('slots').replaceChildren();letters.forEach((_,i)=>{const b=document.createElement('button');b.className='slot'+(selected[i]!==undefined?' filled':'');b.dataset.slot=i;b.textContent=selected[i]!==undefined?letters[selected[i]]:'·';b.setAttribute('aria-label',selected[i]!==undefined?`Remove ${letters[selected[i]]} from position ${i+1}`:`Empty position ${i+1}`);b.disabled=solved||selected[i]===undefined;b.onclick=e=>remove(i,e.detail===0);$('slots').append(b)});$('letters').replaceChildren();letters.forEach((letter,i)=>{const b=document.createElement('button');b.className='tile';b.textContent=letter;b.dataset.tile=i;b.setAttribute('aria-label',`Add letter ${letter}`);b.disabled=solved||selected.includes(i);b.onclick=e=>add(i,e.detail===0);$('letters').append(b)});$('check').disabled=solved||selected.length!==letters.length;$('undo').disabled=solved||selected.length===0;$('clear').disabled=solved||selected.length===0;$('hint').disabled=solved;$('stars').textContent=`★ ${stars} independent words`}
 function add(i,focus){const slot=selected.length;selected.push(i);draw();if(focus)document.querySelector(`[data-slot="${slot}"]`)?.focus({preventScroll:true})}
 function remove(i,focus){const tile=selected[i];selected.splice(i,1);draw();if(focus)document.querySelector(`[data-tile="${tile}"]`)?.focus({preventScroll:true})}
 function check(){if(solved||selected.length!==letters.length)return;if(selected.map(i=>letters[i]).join('')===deck[index][0]){solved=true;if(!helped)stars++;else tricky.push(deck[index]);$('message').textContent='Your word has bloomed!';$('sentence').textContent=deck[index][3].replace('___',deck[index][0]);$('explanation').textContent=`${deck[index][0].toUpperCase()} — ${deck[index][2]}`;$('next').textContent=index===deck.length-1?'See my garden →':'Next word →';$('next').classList.remove('hidden');draw();$('next').focus({preventScroll:true})}else{helped=true;$('message').textContent='Almost — try a different order.';$('explanation').textContent='Tap a filled space to remove a letter, clear the word, or use a hint.'}}
 function finish(){$('play').classList.add('hidden');$('results').classList.remove('hidden');$('result-title').textContent=review?'Practice complete!':`${garden.name} has bloomed!`;$('result-text').textContent=`You built ${deck.length} words and spelled ${stars} without hints or corrections. ${tricky.length?'Practise your tricky words again to help them stick.':'Ready for another garden?'}`;$('review').classList.toggle('hidden',tricky.length===0);if(!review){try{const data=records();data[garden.id]={complete:true,best:Math.max(Number(data[garden.id]?.best)||0,stars)};localStorage.setItem('sprout-word-gardens',JSON.stringify(data))}catch{}}$('results').scrollIntoView({block:'center'})}
 $('check').onclick=check;$('undo').onclick=()=>{if(!solved){selected.pop();draw()}};$('clear').onclick=()=>{if(!solved){selected=[];draw()}};$('hint').onclick=()=>{if(solved)return;helped=true;selected=hint(deck[index][0],letters,selected);$('message').textContent='Here is the next part of your word.';$('explanation').textContent='Keep these letters in order, then add the remaining tiles.';draw()};$('next').onclick=()=>{if(!solved)return;index++;if(index<deck.length)show();else{solved=false;finish()}};$('back').onclick=map;$('return').onclick=map;$('review').onclick=()=>start(garden,[...tricky]);
 document.addEventListener('keydown',e=>{if(e.repeat||e.ctrlKey||e.metaKey||e.altKey||$('play').classList.contains('hidden')||solved)return;if(/^[a-z]$/i.test(e.key)){e.preventDefault();const i=letters.findIndex((c,i)=>c===e.key.toLowerCase()&&!selected.includes(i));if(i>=0)add(i,true)}else if(e.key==='Backspace'){e.preventDefault();if(selected.length)remove(selected.length-1,true)}else if(e.key==='Enter'&&e.target.tagName!=='BUTTON'){e.preventDefault();check()}});map();
})();
