(()=>{
const $=id=>document.getElementById(id),{notes,levels,frequency}=MelodyMeadow;let levelIndex=0,position=0,mistakes=0,phase='ready',sound=true,context=null,timers=[],flashTimer=null,generation=0;const voices=new Set();
function saved(){try{const data=JSON.parse(localStorage.getItem('sprout-melody-meadow')||'{}');return data&&typeof data==='object'&&!Array.isArray(data)?data:{}}catch{return {}}}
function silence(){voices.forEach(v=>{try{v.stop()}catch{}});voices.clear()}
function cancel(){generation++;timers.forEach(clearTimeout);timers=[];clearTimeout(flashTimer);document.querySelectorAll('.pad').forEach(b=>b.classList.remove('lit'));silence()}
async function tone(i){if(!sound)return;const current=generation;try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw Error('No audio');if(!context)context=new Audio();if(context.state==='suspended')await context.resume();if(!sound||document.hidden||current!==generation)return;const osc=context.createOscillator(),gain=context.createGain();osc.type='sine';osc.frequency.value=frequency(notes[i].midi);gain.gain.setValueAtTime(0,context.currentTime);gain.gain.linearRampToValueAtTime(.12,context.currentTime+.015);gain.gain.exponentialRampToValueAtTime(.001,context.currentTime+.36);osc.connect(gain);gain.connect(context.destination);voices.add(osc);osc.onended=()=>{voices.delete(osc);osc.disconnect();gain.disconnect()};osc.start();osc.stop(context.currentTime+.38)}catch{sound=false;$('sound').textContent='Visual mode';$('sound').setAttribute('aria-pressed','false')}}
function light(i){document.querySelectorAll('.pad').forEach(b=>b.classList.remove('lit'));document.querySelectorAll('.pad')[i].classList.add('lit');clearTimeout(flashTimer);flashTimer=setTimeout(()=>document.querySelectorAll('.pad').forEach(b=>b.classList.remove('lit')),340);tone(i)}
function nav(){const data=saved();$('levels').replaceChildren();levels.forEach((l,i)=>{const b=document.createElement('button');b.dataset.level=i;b.textContent=`${i+1}${data[i]?' ✓':''}`;b.setAttribute('aria-label',`Melody ${i+1}: ${l.name}`);b.setAttribute('aria-pressed',String(i===levelIndex));b.onclick=()=>load(i);$('levels').append(b)});$('badges').textContent=`${levels.filter((_,i)=>data[i]).length} / 6 melody badges`}
function draw(){const level=levels[levelIndex];$('phase').textContent={ready:'Ready to listen',listen:'Listen and watch…',answer:'Your turn — repeat the tune',won:'Melody complete!',free:'Free play — make your own tune'}[phase];$('sequence').replaceChildren();level.sequence.forEach((_,i)=>{const dot=document.createElement('span');dot.textContent=i<position?'♪':i+1;dot.className=i<position?'done':i===position&&(phase==='answer'||phase==='listen')?'active':'';dot.setAttribute('aria-label',`Note ${i+1}${i<position?' completed':''}`);$('sequence').append(dot)});document.querySelectorAll('.pad').forEach(b=>b.disabled=!['answer','free'].includes(phase));$('pace').disabled=phase==='listen';$('listen').textContent=phase==='listen'?'Restart the tune ▶':'Listen to the tune ▶';$('free').setAttribute('aria-pressed',String(phase==='free'))}
function load(i){cancel();levelIndex=i;position=0;mistakes=0;phase='ready';$('title').textContent=`${i+1}. ${levels[i].name}`;$('message').textContent='Listen first, then play the notes in order.';$('lesson').textContent=levels[i].lesson;$('next').classList.add('hidden');nav();draw()}
function listen(){cancel();position=0;phase='listen';$('next').classList.add('hidden');$('message').textContent='Watch the flowers and listen to the melody.';$('lesson').textContent=levels[levelIndex].lesson;draw();const gap=$('pace').value==='slow'?760:540;levels[levelIndex].sequence.forEach((note,i)=>{const play=()=>{position=i;draw();light(note)};if(i===0)play();else timers.push(setTimeout(play,i*gap))});timers.push(setTimeout(()=>{phase='answer';position=0;$('message').textContent='Your turn! Repeat the tune from the beginning.';draw()},levels[levelIndex].sequence.length*gap))}
function play(i){if(!['answer','free'].includes(phase))return;light(i);if(phase==='free'){$('message').textContent=`You played ${notes[i].name} (${notes[i].label}).`;$('lesson').textContent='Try repeating a pattern or moving from low notes to high notes.';return}const wanted=levels[levelIndex].sequence[position];if(i!==wanted){mistakes++;position=0;$('message').textContent=`That note was ${notes[i].name}. Try starting again.`;$('lesson').textContent=`The next note was ${notes[wanted].name} (${notes[wanted].label}). Listen again whenever you like.`;draw();return}position++;if(position===levels[levelIndex].sequence.length){phase='won';const stars=Math.max(1,3-Math.min(2,mistakes));try{const data=saved();data[levelIndex]=Math.max(Number(data[levelIndex])||0,stars);localStorage.setItem('sprout-melody-meadow',JSON.stringify(data))}catch{}nav();$('message').textContent=`Melody complete! ${'★'.repeat(stars)}`;$('lesson').textContent=levels[levelIndex].lesson;$('next').textContent=levelIndex===levels.length-1?'Play the first melody again →':'Next melody →';$('next').classList.remove('hidden')}else{$('message').textContent='That’s it — keep the melody going.'}draw()}
notes.forEach((note,i)=>{const b=document.createElement('button');b.className='pad';b.dataset.note=i;b.style.background=note.colour;b.innerHTML=`<span class="flower" aria-hidden="true">${note.icon}</span><b>${note.name} · ${note.label}</b><small>KEY ${i+1}</small>`;b.setAttribute('aria-label',`Play ${note.name}, ${note.label}`);b.onclick=()=>play(i);$('pads').append(b)});$('listen').onclick=listen;$('sound').onclick=()=>{sound=!sound;if(!sound)silence();$('sound').textContent=sound?'Sound on ♪':'Sound off';$('sound').setAttribute('aria-pressed',String(sound))};$('free').onclick=()=>{if(phase==='free'){load(levelIndex);return}cancel();phase='free';position=0;$('next').classList.add('hidden');$('message').textContent='Make a melody of your own.';$('lesson').textContent='Tap any flower. Choose Listen to return to the challenge.';draw()};$('next').onclick=()=>load((levelIndex+1)%levels.length);document.addEventListener('keydown',e=>{if(!e.repeat&&!e.ctrlKey&&!e.metaKey&&!e.altKey&&['1','2','3','4'].includes(e.key)&&e.target.tagName!=='SELECT'){e.preventDefault();play(Number(e.key)-1)}});document.addEventListener('visibilitychange',()=>{if(document.hidden){const wasPlaying=phase==='listen';cancel();if(wasPlaying){phase='ready';position=0;$('message').textContent='Playback stopped while you were away. Listen again when ready.';draw()}}});load(0);
})();
