const OPENINGS=[
 {id:'italian',name:'Italian Game',family:'Open game',description:'Develop quickly and aim at the vulnerable f7 square.',idea:'White develops the bishop actively to c4. Both sides bring out minor pieces before choosing a central pawn break.',line:['e2e4','e7e5','g1f3','b8c6','f1c4','f8c5','c2c3','g8f6']},
 {id:'spanish',name:'Ruy Lopez',family:'Open game',description:'Put pressure on the defender of the e5 pawn.',idea:'Bb5 questions the knight on c6. White usually castles early and builds a long-term claim to the center.',line:['e2e4','e7e5','g1f3','b8c6','f1b5','a7a6','b5a4','g8f6','e1g1','f8e7']},
 {id:'sicilian',name:'Sicilian Defense',family:'Semi-open game',description:'Challenge the center from the c-file.',idea:'Black trades a flank pawn for White’s central d-pawn. The resulting imbalance gives both sides chances.',line:['e2e4','c7c5','g1f3','d7d6','d2d4','c5d4','f3d4','g8f6','b1c3','a7a6']},
 {id:'french',name:'French Defense',family:'Semi-open game',description:'Build a sturdy center, then challenge it.',idea:'Black supports d5 with e6. In this Advance line, c5 attacks the base of White’s pawn chain on d4.',line:['e2e4','e7e6','d2d4','d7d5','e4e5','c7c5','c2c3','b8c6']},
 {id:'caro',name:'Caro–Kann Defense',family:'Semi-open game',description:'Support the d5 break with your c-pawn.',idea:'Black gets a sound pawn structure and develops the light-square bishop before playing e6 in many lines.',line:['e2e4','c7c6','d2d4','d7d5','b1c3','d5e4','c3e4','c8f5']},
 {id:'queens-gambit',name:'Queen’s Gambit Declined',family:'Closed game',description:'Use a wing pawn to challenge Black’s center.',idea:'White’s c4 pawn pressures d5. Black reinforces d5 with e6, and both sides develop toward a central struggle.',line:['d2d4','d7d5','c2c4','e7e6','b1c3','g8f6','c1g5','f8e7']},
 {id:'kings-indian',name:'King’s Indian Defense',family:'Indian defense',description:'Develop the bishop on the long diagonal.',idea:'Black allows White to occupy the center and prepares to strike back with a pawn break, often e5 or c5.',line:['d2d4','g8f6','c2c4','g7g6','b1c3','f8g7','e2e4','d7d6','g1f3','e8g8']},
 {id:'london',name:'London System',family:'Closed game',description:'Build a familiar setup around an active bishop.',idea:'White develops the bishop outside the pawn chain before playing e3. The setup is flexible, but you still need to react to Black’s moves.',line:['d2d4','d7d5','g1f3','g8f6','c1f4','e7e6','e2e3','f8d6','f4g3','e8g8']}
];
if(typeof module!=='undefined')module.exports=OPENINGS;
