(() => {
  const C=ChessCore,S=StudyCore,$=s=>document.querySelector(s);
  const glyph={k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'}, names={k:'king',q:'queen',r:'rook',b:'bishop',n:'knight',p:'pawn'};
  let line={states:[C.initial()],notation:[],uci:[],fullmove:1,result:'*'},cursor=0,selected=null,flipped=false,dirty=false,studyTitle='A fresh perspective',notes='',pendingPromotion=null,pendingReplace=null,deleteId=null,toastTimer,searchGeneration=0;
  let studies=[],completed=[];
  try{const data=JSON.parse(localStorage.getItem('chess-club-studies-v1'));if(Array.isArray(data))studies=data.filter(x=>x&&typeof x.id==='string'&&typeof x.title==='string').slice(0,100)}catch{}
  try{const data=JSON.parse(localStorage.getItem('chess-club-openings-v1'));if(Array.isArray(data))completed=data.filter(x=>typeof x==='string')}catch{}
  function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4000)}
  function storeStudies(next){try{localStorage.setItem('chess-club-studies-v1',JSON.stringify(next));studies=next;return true}catch{toast('Browser storage is unavailable or full. Download a PGN or backup to keep your work.');return false}}
  function tab(name){document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==name);document.querySelectorAll('.nav').forEach(el=>{el.classList.toggle('active',el.dataset.tab===name);el.setAttribute('aria-current',el.dataset.tab===name?'page':'false')});if(name==='library')renderLibrary();if(name==='openings')renderCatalog();window.scrollTo({top:0,behavior:'instant'})}
  document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
  document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());
  function fullmoveAt(index){return line.fullmove+Math.floor((index+(line.states[0].turn==='b'?1:0))/2)}
  function board(target,state,selection,onSquare,reverse=false,highlight=[]){const container=$(target);container.innerHTML='';const legal=selection===null?[]:C.legal(state,selection);for(let visual=0;visual<64;visual++){const i=reverse?63-visual:visual,p=state.board[i],r=Math.floor(i/8),c=i%8,b=document.createElement('button');b.className='square'+((r+c)%2?' dark':'')+(highlight.includes(i)?' last':'')+(selection===i?' selected':'')+(legal.some(m=>m.to===i)?' legal'+(p?' capture':''):'')+(p?.toLowerCase()==='k'&&C.color(p)===state.turn&&C.check(state,state.turn)?' check':'');b.setAttribute('aria-label',C.square(i)+(p?' '+(C.color(p)==='w'?'White ':'Black ')+names[p.toLowerCase()]:' empty'));b.setAttribute('aria-pressed',selection===i);b.innerHTML=(p?`<span class="piece ${C.color(p)==='w'?'white':'black'}">${glyph[p.toLowerCase()]}</span>`:'')+(visual%8===0?`<span class="coord rank">${8-r}</span>`:'')+(visual>=56?`<span class="coord file">${'abcdefgh'[c]}</span>`:'');b.onclick=()=>onSquare(i);b.onkeydown=e=>{const d={ArrowLeft:-1,ArrowRight:1,ArrowUp:-8,ArrowDown:8}[e.key];if(d){e.preventDefault();container.children[Math.max(0,Math.min(63,visual+d))].focus()}};container.append(b)}}
  function render(){const state=line.states[cursor],last=cursor?line.uci[cursor-1]:null;board('#analysis-board',state,selected,choose,flipped,last?[C.indexOfSquare(last.slice(0,2)),C.indexOfSquare(last.slice(2,4))]:[]);$('#turn').textContent=(state.turn==='w'?'White':'Black')+' to move';$('#position-count').textContent=`Ply ${cursor} of ${line.notation.length}`;$('#study-title').textContent=studyTitle;$('#fen').value=S.toFEN(state,fullmoveAt(cursor));const end=C.getOutcome(state,line.states.slice(0,cursor));$('#position-status').textContent=end?end.title+'. '+end.detail:C.check(state,state.turn)?'Check. Find a safe response.':'Explore freely. Both sides are yours to move.';$('#first').disabled=$('#previous').disabled=cursor===0;$('#last').disabled=$('#next').disabled=cursor===line.states.length-1;$('#moves').innerHTML='';let number=line.fullmove;line.notation.forEach((san,i)=>{const side=line.states[i].turn,b=document.createElement('button');b.textContent=(side==='w'?number+'. ':i===0?number+'... ':'')+san;if(side==='b')number++;b.className=i+1===cursor?'active':'';b.onclick=()=>jump(i+1);$('#moves').append(b)});}
  function clearSearch(){searchGeneration++;$('#candidates').innerHTML='';$('#suggest').disabled=false;$('#suggest').textContent='Find candidate moves'}
  function jump(index){cursor=index;selected=null;clearSearch();render()}
  function choose(i){const state=line.states[cursor],move=selected===null?null:C.legal(state,selected).find(m=>m.to===i);if(!move){selected=C.color(state.board[i])===state.turn?(selected===i?null:i):null;return render()}if(state.board[move.from].toLowerCase()==='p'&&(move.to<8||move.to>=56)){pendingPromotion=move;$('#promotion-dialog').showModal();return}makeMove(move)}
  function makeMove(move){const state=line.states[cursor],next=C.apply(state,move);line.states=line.states.slice(0,cursor+1);line.notation=line.notation.slice(0,cursor);line.uci=line.uci.slice(0,cursor);line.states.push(next);line.notation.push(C.completeNotation(state,move,next));line.uci.push(C.square(move.from)+C.square(move.to)+(move.promotion||''));line.result='*';cursor++;selected=null;dirty=true;clearSearch();render()}
  for(const p of ['q','r','b','n']){const b=document.createElement('button');b.textContent=glyph[p];b.setAttribute('aria-label','Promote to '+names[p]);b.onclick=()=>{if(pendingPromotion)makeMove({...pendingPromotion,promotion:p});pendingPromotion=null;$('#promotion-dialog').close()};$('#promotion-options').append(b)}$('#promotion-dialog').addEventListener('close',()=>pendingPromotion=null);
  function replace(action){if(dirty){pendingReplace=action;$('#replace-dialog').showModal()}else action()}
  $('#confirm-replace').onclick=()=>{const action=pendingReplace;pendingReplace=null;$('#replace-dialog').close();action?.()};$('#replace-dialog').addEventListener('close',()=>pendingReplace=null);
  function load(next,title='Untitled study',position=next.states.length-1,nextNotes=''){line=next;cursor=Math.max(0,Math.min(position,next.states.length-1));selected=null;studyTitle=title;notes=nextNotes;$('#study-notes').value=notes;dirty=false;clearSearch();render();tab('analysis')}
  $('#new-position').onclick=()=>replace(()=>load({states:[C.initial()],notation:[],uci:[],fullmove:1,result:'*'},'A fresh perspective'));
  $('#first').onclick=()=>jump(0);$('#previous').onclick=()=>jump(Math.max(0,cursor-1));$('#next').onclick=()=>jump(Math.min(line.states.length-1,cursor+1));$('#last').onclick=()=>jump(line.states.length-1);$('#flip').onclick=()=>{flipped=!flipped;render()};
  $('#load-fen').onclick=()=>{try{const parsed=S.parseFEN($('#fen').value);replace(()=>load({states:[parsed.state],notation:[],uci:[],fullmove:parsed.fullmove,result:'*'},'Imported position'))}catch(error){toast(error.message)}};
  $('#copy-fen').onclick=async()=>{const text=S.toFEN(line.states[cursor],fullmoveAt(cursor));try{await navigator.clipboard.writeText(text);toast('FEN copied.')}catch{$('#fen').value=text;$('#fen').select();toast('FEN selected. Press Ctrl+C or ⌘C to copy.')}};
  function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  $('#export-pgn').onclick=()=>download(S.exportPGN(line,studyTitle),'chess-club-study.pgn','application/x-chess-pgn');
  $('#open-import').onclick=()=>{$('#import-error').textContent='';$('#import-dialog').showModal()};
  $('#pgn-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>100000){$('#import-error').textContent='Choose a PGN smaller than 100 KB.';return}$('#pgn-input').value=await file.text()};
  $('#import-pgn').onclick=()=>{try{const parsed=S.parsePGN($('#pgn-input').value);$('#import-dialog').close();replace(()=>load(parsed,parsed.title))}catch(error){$('#import-error').textContent=error.message}};
  $('#load-game').onclick=()=>{try{const data=JSON.parse(localStorage.getItem('chess-club-v2'));if(!data||!Array.isArray(data.notation)||!data.notation.length)throw Error('No saved local game found. Play a game on the main site first.');const text=data.notation.map((m,i)=>(i%2===0?(i/2+1)+'. ':'')+m).join(' ')+' *';const parsed=S.parsePGN(text);replace(()=>load(parsed,'My last local game'))}catch(error){toast(error.message)}};
  $('#suggest').onclick=()=>{const generation=++searchGeneration,position=line.states[cursor];$('#suggest').disabled=true;$('#suggest').textContent='Looking at replies…';setTimeout(()=>{if(generation!==searchGeneration)return;const candidates=S.suggestions(position);$('#candidates').innerHTML='';for(const candidate of candidates){const b=document.createElement('button');b.className='candidate';const name=document.createElement('strong'),score=document.createElement('span');name.textContent=candidate.san;score.textContent=Math.abs(candidate.score)>=100000?'Mate found':(candidate.score>=0?'+':'')+(candidate.score/100).toFixed(2);b.append(name,score);b.onclick=()=>{if(line.states[cursor]===position)makeMove(candidate.move)};$('#candidates').append(b)}if(!candidates.length)$('#candidates').textContent='No legal moves in this position.';$('#suggest').disabled=false;$('#suggest').textContent='Find candidate moves'},30)};
  $('aside').insertAdjacentHTML('beforeend','<section class="card"><h3>Your notes</h3><label for="study-notes">Ideas to remember</label><textarea id="study-notes" rows="4" maxlength="5000" placeholder="Why does this move work? What would you try next?"></textarea><p class="subtle">Notes are included when you save or back up a study.</p></section>');$('#study-notes').oninput=()=>{notes=$('#study-notes').value;dirty=true};
  $('#save-study').onclick=()=>{$('#save-title').value=studyTitle==='A fresh perspective'?'':studyTitle;$('#save-dialog').showModal();$('#save-title').focus()};
  function newId(){return typeof crypto.randomUUID==='function'?crypto.randomUUID():Date.now().toString(36)+'-'+Math.random().toString(36).slice(2)}
  $('#confirm-save').onclick=()=>{const title=$('#save-title').value.trim()||'Untitled study';if(studies.length>=100)return toast('Your shelf holds 100 studies. Back up and remove a study to make room.');const study={id:newId(),title:title.slice(0,80),fen:S.toFEN(line.states[0],line.fullmove),moves:[...line.uci],cursor,result:line.result||'*',notes:notes.slice(0,5000),updated:new Date().toISOString()};if(storeStudies([study,...studies])){studyTitle=title;dirty=false;$('#save-dialog').close();render();toast('Study saved to your shelf.')}};
  function restoreLine(study){if(!study||typeof study.title!=='string'||study.title.length>80||typeof study.fen!=='string'||!Array.isArray(study.moves)||study.moves.length>1000)throw Error('Invalid study in backup.');const root=S.parseFEN(study.fen),restored={states:[root.state],notation:[],uci:[],fullmove:root.fullmove,result:['*','1-0','0-1','1/2-1/2'].includes(study.result)?study.result:'*'};for(const uci of study.moves){if(typeof uci!=='string'||!/^[a-h][1-8][a-h][1-8][qrbn]?$/.test(uci))throw Error('Invalid move in saved study.');const state=restored.states.at(-1),m=C.moveFromUCI(state,uci);if(!m)throw Error('A saved study contains an illegal move.');const next=C.apply(state,m);restored.notation.push(C.completeNotation(state,m,next));restored.uci.push(uci);restored.states.push(next)}return restored}
  function renderLibrary(){const query=$('#study-search').value.trim().toLowerCase(),filtered=studies.filter(s=>s.title.toLowerCase().includes(query));$('#library-grid').innerHTML='';$('#library-empty').hidden=filtered.length>0;if(!filtered.length){$('#library-empty h3').textContent=studies.length?'No matching studies.':'A home for your next discovery.';$('#library-empty p').textContent=studies.length?'Try a different search.':'Explore a position, then choose Save study to keep it here.'}for(const study of filtered){const card=document.createElement('article');card.className='opening-card';const eyebrow=document.createElement('span');eyebrow.className='eyebrow';eyebrow.textContent='Saved study';const title=document.createElement('h3');title.textContent=study.title;const info=document.createElement('p');info.textContent=(study.moves?.length||0)+' plies · '+(Number.isNaN(Date.parse(study.updated))?'Saved locally':new Date(study.updated).toLocaleDateString());const open=document.createElement('button');open.className='primary';open.textContent='Open study';open.onclick=()=>{try{const restored=restoreLine(study);replace(()=>load(restored,study.title,Number.isInteger(study.cursor)?study.cursor:restored.states.length-1,typeof study.notes==='string'?study.notes:''))}catch(error){toast(error.message)}};const remove=document.createElement('button');remove.className='danger';remove.textContent='Delete';remove.onclick=()=>{deleteId=study.id;$('#delete-title').textContent=study.title;$('#delete-dialog').showModal()};card.append(eyebrow,title,info,open,remove);$('#library-grid').append(card)}}
  $('#study-search').oninput=renderLibrary;$('#confirm-delete').onclick=()=>{if(storeStudies(studies.filter(s=>s.id!==deleteId))){$('#delete-dialog').close();deleteId=null;renderLibrary()}};
  $('#backup-studies').onclick=()=>download(JSON.stringify({version:1,studies},null,2),'chess-club-studies.json','application/json');
  $('#restore-studies').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2000000)throw Error('Choose a backup smaller than 2 MB.');const data=JSON.parse(await file.text());if(data.version!==1||!Array.isArray(data.studies)||data.studies.length>100)throw Error('This is not a Rookavelle Chess Academy ♛ study backup.');const additions=[];for(const study of data.studies){restoreLine(study);if(studies.concat(additions).some(s=>s.title===study.title&&s.fen===study.fen&&JSON.stringify(s.moves)===JSON.stringify(study.moves)))continue;additions.push({...study,id:newId(),notes:typeof study.notes==='string'?study.notes.slice(0,5000):'',updated:new Date().toISOString()})}if(studies.length+additions.length>100)throw Error('The restored shelf would exceed 100 studies.');if(storeStudies([...additions,...studies])){renderLibrary();toast(additions.length+' studies restored.')}}catch(error){toast(error.message)}finally{e.target.value=''}};
  let trainer=null,trainerTimer;
  function renderCatalog(){$('#opening-progress').textContent=completed.length+' / 16 sides practiced';$('#opening-catalog').innerHTML='';for(const opening of OPENINGS){const b=document.createElement('button');b.className='opening-card';b.innerHTML=`<span class="eyebrow">${opening.family}</span><h3>${opening.name}</h3><p>${opening.description}</p><span class="completed">${completed.includes(opening.id+':w')?'✓ White':'White'} · ${completed.includes(opening.id+':b')?'✓ Black':'Black'} &nbsp; →</span>`;b.onclick=()=>startOpening(opening);$('#opening-catalog').append(b)}}
  function openingFeedback(text,success=false){$('#trainer-feedback').textContent=text;$('#trainer-feedback').className='notice'+(success?' success':'')}
  function startOpening(opening){clearTimeout(trainerTimer);trainer={opening,state:C.initial(),index:0,selected:null,side:$('#practice-side').value,busy:false,done:false,notation:[]};$('#opening-catalog').hidden=true;$('#opening-trainer').hidden=false;$('#opening-title').textContent=opening.name;$('#opening-family').textContent=opening.family;$('#opening-idea').textContent=opening.idea;openingFeedback('Play the first move of this reference line.');renderTrainer();autoReply()}
  function renderTrainer(highlight=[]){board('#opening-board',trainer.state,trainer.selected,chooseOpening,trainer.side==='b',highlight);$('#trainer-turn').textContent=trainer.done?'Line complete':trainer.state.turn===trainer.side?'Your move':'Reference reply';$('#trainer-progress').textContent=`${trainer.index} / ${trainer.opening.line.length} plies`;$('#trainer-bar').style.width=(trainer.index/trainer.opening.line.length*100)+'%';$('#opening-line').innerHTML='';trainer.notation.forEach((san,i)=>{const span=document.createElement('span');span.textContent=(i%2===0?(i/2+1)+'. ':'')+san+' ';$('#opening-line').append(span)});$('#opening-hint').disabled=trainer.done||trainer.busy}
  function advanceOpening(move){trainer.state=C.apply(trainer.state,move);trainer.index++;trainer.selected=null;if(trainer.index===trainer.opening.line.length){trainer.done=true;const key=trainer.opening.id+':'+trainer.side;if(!completed.includes(key)){completed.push(key);try{localStorage.setItem('chess-club-openings-v1',JSON.stringify(completed))}catch{toast('Opening completed, but browser storage is unavailable.')}}openingFeedback('Line complete. '+trainer.opening.idea,true);renderCatalog()}renderTrainer([move.from,move.to]);}
  function chooseOpening(i){if(!trainer||trainer.done||trainer.busy||trainer.state.turn!==trainer.side)return;const move=trainer.selected===null?null:C.legal(trainer.state,trainer.selected).find(m=>m.to===i);if(!move){trainer.selected=C.color(trainer.state.board[i])===trainer.side?(trainer.selected===i?null:i):null;return renderTrainer()}const uci=C.square(move.from)+C.square(move.to);if(uci!==trainer.opening.line[trainer.index]){trainer.selected=null;openingFeedback('That is a legal move, but it leaves this reference line. Try another move or ask for a hint.');return renderTrainer()}trainer.notation.push(C.completeNotation(trainer.state,move,C.apply(trainer.state,move)));advanceOpening(move);if(!trainer.done){openingFeedback('Good. Watch the reference reply.');autoReply()}}
  function autoReply(){if(!trainer||trainer.done||trainer.state.turn===trainer.side)return;trainer.busy=true;renderTrainer();const active=trainer;trainerTimer=setTimeout(()=>{if(trainer!==active)return;const move=C.moveFromUCI(trainer.state,trainer.opening.line[trainer.index]);trainer.notation.push(C.completeNotation(trainer.state,move,C.apply(trainer.state,move)));trainer.busy=false;advanceOpening(move);if(!trainer.done)openingFeedback('Your turn. Continue the reference line.')},500)}
  $('#practice-side').onchange=()=>{if(trainer)startOpening(trainer.opening)};$('#restart-opening').onclick=()=>startOpening(trainer.opening);$('#back-openings').onclick=()=>{clearTimeout(trainerTimer);trainer=null;$('#opening-catalog').hidden=false;$('#opening-trainer').hidden=true;renderCatalog()};
  $('#opening-hint').onclick=()=>{if(!trainer||trainer.done||trainer.busy)return;const m=C.moveFromUCI(trainer.state,trainer.opening.line[trainer.index]);openingFeedback('Try '+C.notationFor(trainer.state,m)+': '+C.square(m.from)+' → '+C.square(m.to)+'.');renderTrainer([m.from,m.to])};
  $('#study-opening').onclick=()=>{const opening=trainer.opening,states=[C.initial()],notation=[],uci=[];for(const text of opening.line){const state=states.at(-1),move=C.moveFromUCI(state,text),next=C.apply(state,move);states.push(next);notation.push(C.completeNotation(state,move,next));uci.push(text)}replace(()=>load({states,notation,uci,fullmove:1,result:'*'},opening.name,states.length-1,opening.idea))};
  document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.target.matches('input,textarea,select')||document.querySelector('dialog[open]')||$('#analysis').hidden)return;if(e.key.toLowerCase()==='f'){e.preventDefault();$('#flip').click()}});
  window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
  render();renderCatalog();renderLibrary();
})();
