(function(){
  const channels=[
    {id:'lichess',name:'Lichess TV',kind:'boards',icon:'♞',type:'Live board',url:'https://lichess.org/tv',description:'A featured game from Lichess, updated by their live board feed.'},
    {id:'chess',name:'Chess.com',kind:'streams',icon:'▶',type:'Twitch channel',channel:'chess',url:'https://www.twitch.tv/chess',description:'Chess.com’s Twitch channel. Watch commentary when a broadcast is running.'},
    {id:'chess24',name:'chess24',kind:'streams',icon:'▶',type:'Twitch channel',channel:'chess24',url:'https://www.twitch.tv/chess24',description:'The chess24 Twitch channel for chess coverage and commentary when broadcasting.'}
  ];
  function parseStreamLink(text){let url;try{url=new URL(text.trim())}catch{throw Error('Paste a complete YouTube video or Twitch channel link.')}if(!['https:','http:'].includes(url.protocol)||url.username||url.password)throw Error('Use a YouTube or Twitch web link.');const host=url.hostname.toLowerCase(),parts=url.pathname.split('/').filter(Boolean);let video;
    if(host==='youtu.be')video=parts.length===1?parts[0]:null;
    else if(['youtube.com','www.youtube.com','m.youtube.com'].includes(host)){if(url.pathname==='/watch')video=url.searchParams.get('v');else if(['live','embed','shorts'].includes(parts[0])&&parts.length===2)video=parts[1]}
    if(video&&/^[\w-]{11}$/.test(video))return {id:'custom-youtube',name:'Your YouTube stream',kind:'video',type:'YouTube video or live broadcast',url:'https://www.youtube.com/watch?v='+video,embed:'https://www.youtube-nocookie.com/embed/'+video+'?autoplay=0&playsinline=1',description:'The selected YouTube video or live broadcast. Playback depends on the publisher’s availability and embedding settings.'};
    if(['twitch.tv','www.twitch.tv','m.twitch.tv'].includes(host)&&parts.length===1&&/^[a-zA-Z0-9_]{1,25}$/.test(parts[0])&&!['directory','downloads','settings','videos','search','subscriptions'].includes(parts[0].toLowerCase())){const channel=parts[0].toLowerCase();return {id:'custom-twitch',name:channel,kind:'streams',type:'Twitch channel',channel,url:'https://www.twitch.tv/'+channel,description:'Your selected Twitch channel. The player shows whether it is currently broadcasting.'}}
    throw Error('Use a YouTube watch/live/video link or a Twitch channel link. Channel homepages and Twitch clips are not supported.');
  }
  function embedURL(source,hostname){if(source.channel){if(!hostname)return null;const url=new URL('https://player.twitch.tv/');url.searchParams.set('channel',source.channel);url.searchParams.set('parent',hostname);url.searchParams.set('autoplay','false');url.searchParams.set('muted','false');return url.href}return source.embed}
  if(typeof module!=='undefined'){module.exports={parseStreamLink,embedURL,channels};return}
  const $=s=>document.querySelector(s);let selected=channels[0],filter='all',favorites=[],stopBoard=null;
  try{const stored=JSON.parse(localStorage.getItem('chess-club-watch-favorites'));if(Array.isArray(stored))favorites=stored.filter(id=>channels.some(c=>c.id===id))}catch{}
  function renderChannels(){$('#channel-list').innerHTML='';const visible=channels.filter(c=>filter==='all'||filter===c.kind||filter==='saved'&&favorites.includes(c.id));$('#empty-channels').hidden=visible.length>0;for(const c of visible){const button=document.createElement('button');button.className='channel-button'+(selected.id===c.id?' selected':'');button.setAttribute('aria-pressed',selected.id===c.id);button.innerHTML=`<span class="channel-icon">${c.icon}</span><span><strong>${c.name}</strong><small>${c.kind==='boards'?'Live game feed':'Live when broadcasting'}</small></span>`;if(favorites.includes(c.id)){const star=document.createElement('span');star.className='channel-star';star.textContent='★';button.append(star)}button.onclick=()=>{selected=c;renderPlayer();renderChannels()};$('#channel-list').append(button)}}
  function placeholder(message){const wrapper=document.createElement('div');wrapper.className='player-placeholder';const symbol=document.createElement('div');symbol.className='symbol';symbol.textContent='▷';const text=document.createElement('p');text.textContent=message;const a=document.createElement('a');a.href=selected.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Watch on original site ↗';wrapper.append(symbol,text,a);$('#player').append(wrapper)}
  function renderPlayer(){stopBoard?.();stopBoard=null;const container=$('#player');container.innerHTML='';container.className='player-shell '+(selected.kind==='boards'?'board-player':'video-player');$('#source-title').textContent=selected.name;$('#source-type').textContent=selected.type;$('#source-description').textContent=selected.description;$('#source-link').href=selected.url;$('#source-link').textContent=selected.kind==='boards'?'Open on Lichess ↗':'Open original ↗';const saved=favorites.includes(selected.id);$('#favorite-source').disabled=!channels.some(c=>c.id===selected.id);$('#favorite-source').textContent=saved?'★ Saved channel':'☆ Save channel';$('#favorite-source').setAttribute('aria-pressed',saved);
    if(!navigator.onLine){placeholder('You are offline. Connect to the internet to watch this source.');$('#player-status').textContent='Internet connection needed.';return}
    if(selected.kind==='boards'){stopBoard=startLiveBoard(container,$('#player-status'),$('#source-link'));return}
    if(selected.channel&&(!location.hostname||container.getBoundingClientRect().width<400)){placeholder(!location.hostname?'Open the channel directly, or open this website through its local server to use the embedded player.':'Open this channel on Twitch for the best experience on a small screen.');$('#player-status').textContent='Twitch’s embedded player needs at least 400 pixels of width.';return}
    const iframe=document.createElement('iframe');iframe.title=selected.name+' player';iframe.src=embedURL(selected,location.hostname);iframe.allow='autoplay; fullscreen; picture-in-picture; encrypted-media';iframe.allowFullscreen=true;iframe.referrerPolicy='strict-origin-when-cross-origin';container.append(iframe);$('#player-status').textContent=selected.kind==='boards'?'Live board supplied by Lichess. If it does not load, open the original.':'If the channel is offline or playback is blocked, open the original site or choose another source.';
    iframe.addEventListener('error',()=>{$('#player-status').textContent='The player could not load. Use Open original to watch on the source site.'});
  }
  document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderChannels()});
  $('#favorite-source').onclick=()=>{if(!channels.some(c=>c.id===selected.id))return;const next=favorites.includes(selected.id)?favorites.filter(id=>id!==selected.id):[...favorites,selected.id];try{localStorage.setItem('chess-club-watch-favorites',JSON.stringify(next));favorites=next;const saved=favorites.includes(selected.id);$('#favorite-source').textContent=saved?'★ Saved channel':'☆ Save channel';$('#favorite-source').setAttribute('aria-pressed',saved);renderChannels()}catch{$('#player-status').textContent='This browser could not save your favorite channels.'}};
  $('#custom-stream').onsubmit=e=>{e.preventDefault();try{const source=parseStreamLink($('#stream-url').value);selected=source;$('#stream-error').textContent='';renderPlayer();renderChannels();$('#source-title').scrollIntoView({behavior:'smooth',block:'center'})}catch(error){$('#stream-error').textContent=error.message}};
  $('#reload-player').onclick=renderPlayer;$('#focus-mode').onclick=()=>{const focused=$('#watch-layout').classList.toggle('focus');$('#focus-mode').setAttribute('aria-pressed',focused);$('#focus-mode').textContent=focused?'Exit focus mode':'⛶ Focus mode';if(selected.channel)renderPlayer()};
  window.addEventListener('offline',renderPlayer);window.addEventListener('online',renderPlayer);let playerFits=$('#player').getBoundingClientRect().width>=400;new ResizeObserver(()=>{const fits=$('#player').getBoundingClientRect().width>=400;if(fits!==playerFits){playerFits=fits;if(selected.channel)renderPlayer()}}).observe($('#player'));
  window.addEventListener('pagehide',()=>stopBoard?.());
  renderChannels();renderPlayer();
})();
