(() => {
 const $=s=>document.querySelector(s),canvas=$('#world'),ctx=canvas.getContext('2d'),game=new Cloudbound.Game(),keys={left:false,right:false};let running=false,paused=false,last=0,camera=0,time=0,best=0,sound=false,audio,oldGems=0,oldLives=3,oldCheckpoint=false;
 const resize=()=>canvas.width=innerWidth<=750?720:960;resize();window.addEventListener('resize',resize);
 try{best=Math.max(0,Math.min(30,Number(localStorage.getItem('cloudbound-best'))||0))}catch{}$('#best').textContent=`BEST EXPEDITION: ${best} / 30 GEMS`;
 function save(){best=Math.max(best,game.collected.size);try{localStorage.setItem('cloudbound-best',best);$('#best').textContent=`BEST EXPEDITION: ${best} / 30 GEMS`}catch{$('#best').textContent=`BEST THIS VISIT: ${best} / 30 GEMS`}}
 function beep(f){if(!sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=f;g.gain.setValueAtTime(.03,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.15);o.start();o.stop(audio.currentTime+.15)}catch{}}
 $('#sound').onclick=()=>{sound=!sound;$('#sound').textContent=sound?'Sound on':'Sound off';$('#sound').setAttribute('aria-pressed',sound);beep(600)};
 function show(title,copy,button,tag){$('#overlay-title').textContent=title;$('#overlay-copy').textContent=copy;$('#start').textContent=button;$('#overlay-tag').textContent=tag;$('#overlay').hidden=false;$('#announce').textContent=title+' '+copy;keys.left=keys.right=false}
 function begin(){if(paused){paused=false}else if(game.status==='level-complete'){game.load(game.levelIndex+1)}else{game.restart()}running=true;game.status='playing';camera=Math.max(0,game.player.x-canvas.width*.3);last=performance.now();oldCheckpoint=game.checkpoint;oldGems=game.collected.size;oldLives=game.lives;$('#overlay').hidden=true;$('#pause').disabled=false;$('#pause').setAttribute('aria-label','Pause game');canvas.focus({preventScroll:true});if($('.game-shell').getBoundingClientRect().bottom>innerHeight)$('.game-shell').scrollIntoView({block:'start',behavior:'instant'});hud()}
 function pause(){if(!running||paused||game.status!=='playing')return;paused=true;show('A moment in the clouds.','Your adventure will be right here.','Keep exploring →','TAKE YOUR TIME');$('#pause').setAttribute('aria-label','Resume game')}
 $('#start').onclick=begin;$('#pause').onclick=()=>paused?begin():pause();
 function jump(){if(running&&!paused&&game.jump())beep(350+game.player.jumps*120)}$('#jump').onpointerdown=e=>{e.preventDefault();jump()};
 for(const side of ['left','right']){const b=$('#'+side);b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);if(running&&!paused)keys[side]=true};for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,()=>keys[side]=false)}
 document.addEventListener('keydown',e=>{if(e.altKey||e.metaKey||e.ctrlKey||e.target.closest('input,textarea,select'))return;if(['KeyP','Escape'].includes(e.code)&&!e.repeat){e.preventDefault();paused?begin():pause();return}if(!running||paused)return;if(['ArrowLeft','KeyA','ArrowRight','KeyD','Space','ArrowUp','KeyW'].includes(e.code)){if(e.code==='Space'&&e.target.closest('button,a'))return;e.preventDefault();if(['ArrowLeft','KeyA'].includes(e.code))keys.left=true;else if(['ArrowRight','KeyD'].includes(e.code))keys.right=true;else if(!e.repeat)jump()}});
 document.addEventListener('keyup',e=>{if(['ArrowLeft','KeyA'].includes(e.code))keys.left=false;if(['ArrowRight','KeyD'].includes(e.code))keys.right=false});window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});
 function hud(){$('#chapter').textContent=`0${game.levelIndex+1} / 03`;$('#level-name').textContent=game.level.name;$('#gems').textContent=game.collected.size;$('#lives').textContent='♥ '.repeat(game.lives)+'♡ '.repeat(3-game.lives);$('#lives').setAttribute('aria-label',game.lives+' lives');$('#checkpoint').textContent=game.checkpoint?'⚑ Checkpoint found. A little place to return to.':'⚑ Find the checkpoint to save your place.'}
 function rect(x,y,w,h,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
 function cloud(x,y,s){ctx.fillStyle='#f9fbeb9c';ctx.beginPath();ctx.ellipse(x,y,64*s,16*s,0,0,Math.PI*2);ctx.ellipse(x-22*s,y-13*s,24*s,22*s,0,0,Math.PI*2);ctx.ellipse(x+13*s,y-18*s,30*s,28*s,0,0,Math.PI*2);ctx.fill()}
 function flag(x,active){ctx.fillStyle='#76948a';ctx.fillRect(x,365,4,75);ctx.fillStyle=active?'#e9b956':'#94aaa0';ctx.beginPath();ctx.moveTo(x+4,366);ctx.lineTo(x+42,375);ctx.lineTo(x+4,391);ctx.fill();ctx.fillStyle='#ffffffaa';ctx.font='17px Arial';ctx.fillText('✦',x+10,384)}
 function draw(){const W=canvas.width;const sky=ctx.createLinearGradient(0,0,0,540);sky.addColorStop(0,'#cde8df');sky.addColorStop(1,'#edf0ce');ctx.fillStyle=sky;ctx.fillRect(0,0,W,540);ctx.fillStyle='#fff3b4';ctx.beginPath();ctx.arc(W*.77-camera*.025,119,43,0,Math.PI*2);ctx.fill();for(let i=0;i<5;i++)cloud((i*280-camera*.15+time*3)%(W+250)-60,110+i%3*40,.75+i%2*.25);
 for(let i=-1;i<6;i++){const x=i*290-camera*.18;ctx.fillStyle='#aecfbb';ctx.beginPath();ctx.moveTo(x,470);ctx.quadraticCurveTo(x+120,110,x+260,470);ctx.fill();ctx.fillStyle='#d9e6c7';ctx.beginPath();ctx.moveTo(x+99,238);ctx.lineTo(x+122,208);ctx.lineTo(x+148,246);ctx.lineTo(x+123,235);ctx.fill()}
 ctx.save();ctx.translate(-camera,0);
 for(const [x,y,w,h] of game.level.platforms){if(x+w<camera||x>camera+W)continue;rect(x,y,w,h,8,'#638f75');rect(x,y+7,w,h-7,6,'#93b594');ctx.fillStyle='#6f9a7d';for(let n=0;n<w;n+=42){ctx.beginPath();ctx.moveTo(x+n,y+h);ctx.lineTo(x+n+16,y+h+18+(n%3)*5);ctx.lineTo(x+n+28,y+h);ctx.fill()}rect(x-2,y,w+4,9,4,'#c0d78d');ctx.fillStyle='#729970';for(let n=12;n<w-7;n+=55){ctx.fillRect(x+n,y+24,8,4);if(h>30)ctx.fillRect(x+n+16,y+47,13,4)}ctx.strokeStyle='#588a6a';ctx.lineWidth=2;for(let n=20;n<w-20;n+=90){ctx.beginPath();ctx.moveTo(x+n,y);ctx.lineTo(x+n-3,y-10);ctx.moveTo(x+n,y);ctx.lineTo(x+n+5,y-7);ctx.stroke()}}
 flag(game.level.checkpoint,game.checkpoint);flag(game.level.goal,true);ctx.fillStyle='#4e7b62';ctx.font='bold 11px Arial';ctx.fillText('HOME',game.level.goal-12,352);
 game.level.gems.forEach(([x,y],i)=>{if(game.collected.has(game.levelIndex+':'+i))return;const bob=Math.sin(time*3+i)*3;ctx.save();ctx.translate(x,y+bob);ctx.fillStyle='#53a8a9';ctx.beginPath();ctx.moveTo(0,-12);ctx.lineTo(9,0);ctx.lineTo(0,12);ctx.lineTo(-9,0);ctx.closePath();ctx.fill();ctx.fillStyle='#b5edce';ctx.beginPath();ctx.moveTo(0,-9);ctx.lineTo(0,8);ctx.lineTo(-6,0);ctx.fill();ctx.restore()});
 for(const e of game.enemies){if(!e.alive)continue;rect(e.x,e.y+5,32,25,10,'#d18a73');ctx.fillStyle='#b47361';ctx.beginPath();ctx.ellipse(e.x+16,e.y+7,18,8,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff3d5';ctx.fillRect(e.x+6,e.y+12,6,6);ctx.fillRect(e.x+21,e.y+12,6,6);ctx.fillStyle='#453f39';ctx.fillRect(e.x+9,e.y+14,3,4);ctx.fillRect(e.x+21,e.y+14,3,4)}
 const p=game.player;ctx.save();if(p.invulnerable>0&&Math.floor(p.invulnerable*12)%2!==0)ctx.globalAlpha=.45;{ctx.fillStyle='#385f5833';ctx.beginPath();ctx.ellipse(p.x+15,p.y+p.h+3,19,5,0,0,Math.PI*2);ctx.fill();rect(p.x,p.y+7,30,29,8,'#337f70');rect(p.x+2,p.y,26,22,9,'#398e7b');rect(p.x+7,p.y+7,19,12,5,'#f9e5b0');ctx.fillStyle='#294840';ctx.fillRect(p.x+13,p.y+10,3,4);ctx.fillRect(p.x+21,p.y+10,3,4);ctx.fillStyle='#eeb872';ctx.fillRect(p.x-4,p.y+23,38,5);const walk=p.grounded&&p.vx?Math.sin(time*17)*3:0;rect(p.x+3,p.y+33,9,7+walk,3,'#28574d');rect(p.x+19,p.y+33,9,7-walk,3,'#28574d')}
 ctx.restore();ctx.restore();const mist=ctx.createLinearGradient(0,480,0,540);mist.addColorStop(0,'#edf0ce00');mist.addColorStop(1,'#edf0ce');ctx.fillStyle=mist;ctx.fillRect(0,480,W,60)}
 function frame(now){let dt=Math.min(.05,(now-last)/1000||0);last=now;if(running&&!paused){while(dt>0){const step=Math.min(dt,1/120);game.step(step,keys);dt-=step}time+=.016;camera=Math.max(0,Math.min(game.level.width-canvas.width,game.player.x-canvas.width*.3));if(game.collected.size>oldGems){oldGems=game.collected.size;beep(870);save()}if(game.lives<oldLives){oldLives=game.lives;beep(150);$('#announce').textContent=`${game.lives} lives remaining.`}if(game.checkpoint&&!oldCheckpoint){oldCheckpoint=true;beep(660);$('#announce').textContent='Checkpoint reached.'}hud();if(game.status!=='playing'){running=false;$('#pause').disabled=true;save();if(game.status==='level-complete')show('A little higher. A little braver.',`${game.level.name} complete. ${game.collected.size} gems found so far.`,'Next chapter →','CHAPTER COMPLETE');else if(game.status==='won')show('You’re cloudbound!',`All three chapters complete! You found ${game.collected.size} of 30 gems.`,'Explore again →','WHAT AN ADVENTURE');else show('Every leap teaches you.',`You found ${game.collected.size} gems. A new adventure is one jump away.`,'Try again →','LET’S HAVE ANOTHER GO')}}draw();requestAnimationFrame(frame)}hud();requestAnimationFrame(frame);
})();
