(() => {
const $=s=>document.querySelector(s),canvas=$('#board'),ctx=canvas.getContext('2d'),game=new OrbitSnake(),speeds={calm:210,cruise:140,comet:90};let pace='cruise',running=false,paused=false,last=0,elapsed=0,records={};try{records=JSON.parse(localStorage.getItem('orbit-snake-best')||'{}')||{}}catch{}
function best(){$('#best').textContent=String(Number(records[pace])||0).padStart(2,'0');$('#record-mode').textContent=pace.toUpperCase()+' MODE RECORD'}best();
function hud(){$('#score').textContent=String(game.score).padStart(2,'0');$('#length').textContent=String(game.body.length).padStart(2,'0');$('#status').textContent=pace.toUpperCase()+' MODE · FOLLOW THE GLOW.'}
function show(title,copy,button,tag){$('#title').textContent=title;$('#copy').textContent=copy;$('#start').textContent=button;$('#tag').textContent=tag;$('#overlay').hidden=false;$('#announce').textContent=title+' '+copy}
function start(){if(paused)paused=false;else game.reset();running=true;elapsed=0;last=performance.now();$('#overlay').hidden=true;$('#pause').disabled=false;$('#pause').setAttribute('aria-label','Pause game');for(const b of $('#speeds').children)b.disabled=true;canvas.focus({preventScroll:true});hud()}
function pause(){if(!running||paused)return;paused=true;show('A moment between orbits.','Your little universe can wait.','Keep growing →','PAUSED');$('#pause').setAttribute('aria-label','Resume game')}
$('#start').onclick=start;$('#pause').onclick=()=>paused?start():pause();for(const b of $('#speeds').children)b.onclick=()=>{pace=b.dataset.speed;for(const c of $('#speeds').children)c.setAttribute('aria-pressed',b===c);best()};
const dirs={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]};function turn(d){if(running&&!paused)game.turn(...dirs[d])}for(const d of Object.keys(dirs))$('#'+d).onpointerdown=e=>{e.preventDefault();turn(d)};
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.target.closest('input,select,textarea'))return;if(['KeyP','Escape'].includes(e.code)&&!e.repeat){paused?start():pause();return}const d={ArrowUp:'up',KeyW:'up',ArrowDown:'down',KeyS:'down',ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right'}[e.code];if(d&&running&&!paused){e.preventDefault();if(!e.repeat)turn(d)}});let swipe;canvas.onpointerdown=e=>{swipe={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId)};canvas.onpointerup=e=>{if(!swipe)return;const dx=e.clientX-swipe.x,dy=e.clientY-swipe.y;if(Math.max(Math.abs(dx),Math.abs(dy))>15)turn(Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up');swipe=null};canvas.onpointercancel=()=>swipe=null;window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});
function rect(x,y,w,h,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function draw(){ctx.fillStyle='#141829';ctx.fillRect(0,0,600,600);ctx.fillStyle='#a995df16';for(let x=0;x<20;x++)for(let y=0;y<20;y++){ctx.beginPath();ctx.arc(x*30+15,y*30+15,1,0,Math.PI*2);ctx.fill()}ctx.strokeStyle='#bfa5ef24';ctx.strokeRect(1,1,598,598);if(game.food){const x=game.food.x*30+15,y=game.food.y*30+15;ctx.save();ctx.translate(x,y);ctx.shadowColor='#ffc68a';ctx.shadowBlur=16;ctx.fillStyle='#ffd19c';ctx.beginPath();for(let i=0;i<8;i++){const r=i%2?6:12,a=i*Math.PI/4;ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r)}ctx.closePath();ctx.fill();ctx.restore()}for(let i=game.body.length-1;i>=0;i--){const p=game.body[i];rect(p.x*30+2,p.y*30+2,26,26,7,i===0?'#d2c2ff':`hsl(${255-i*.6} 53% ${Math.max(40,69-i*.8)}%)`)}const h=game.body[0],d=game.direction;ctx.fillStyle='#3c2b64';for(const s of [-1,1]){ctx.beginPath();ctx.arc(h.x*30+15+d.x*6+d.y*s*5,h.y*30+15+d.y*6+d.x*s*5,2.2,0,Math.PI*2);ctx.fill()}}
function frame(now){const dt=Math.min(now-last,250);last=now;if(running&&!paused){elapsed+=dt;if(elapsed>=speeds[pace]){elapsed-=speeds[pace];game.step();hud();if(game.status!=='playing'){running=false;$('#pause').disabled=true;for(const b of $('#speeds').children)b.disabled=false;if(game.score>(Number(records[pace])||0)){records[pace]=game.score;try{localStorage.setItem('orbit-snake-best',JSON.stringify(records))}catch{$('#record-note').textContent='Best for this visit. Storage unavailable.'}best()}show(game.status==='won'?'A whole universe, explored.':'A beautiful little orbit.',`${game.score} stars collected. ${game.body.length} segments long. Ready for another?`,'One more orbit →',game.status==='won'?'YOU FILLED THE SKY':'TRY A NEW PATH')}}}draw();requestAnimationFrame(frame)}hud();requestAnimationFrame(frame);
})();
