(()=>{
const $=id=>document.getElementById(id),{labs,shuffle}=ScienceSorter;let lab,deck=[],index=0,score=0,missed=[],answered=false,reviewing=false;
function saved(){try{const value=JSON.parse(localStorage.getItem('sprout-science-labs')||'{}');return value&&typeof value==='object'&&!Array.isArray(value)?value:{}}catch{return {}}}
function home(){const data=saved();$('badges').textContent=`${labs.filter(l=>data[l.id]?.complete).length} / 3 lab badges`;$('labs').replaceChildren();for(const item of labs){const b=document.createElement('button');b.className='lab';b.dataset.lab=item.id;b.innerHTML=`<span aria-hidden="true">${item.icon}</span><b>${item.name}</b><p>${item.description}</p><small>${data[item.id]?.complete?`✓ Badge earned · best ${Number(data[item.id].best)||0} / 8`:'8 discoveries · Enter the lab →'}</small>`;b.onclick=()=>start(item);$('labs').append(b)}$('home').classList.remove('hidden');$('play').classList.add('hidden');$('results').classList.add('hidden')}
function start(item,cards){lab=item;deck=shuffle(cards||item.cards);reviewing=!!cards;index=0;score=0;missed=[];$('home').classList.add('hidden');$('play').classList.remove('hidden');$('results').classList.add('hidden');show();$('play').scrollIntoView({block:'start'})}
function show(){answered=false;const row=deck[index];$('icon').textContent=row[1];$('prompt').textContent=row[0];$('lab-name').textContent=lab.name+(reviewing?' · PRACTICE':'');$('step').textContent=`Card ${index+1} / ${deck.length}`;$('score').textContent=`★ ${score} correct`;$('progress').replaceChildren();deck.forEach((_,i)=>{const dot=document.createElement('span');dot.className=i<index?'done':i===index?'current':'';dot.setAttribute('aria-label',`Card ${i+1}${i<index?' completed':''}`);$('progress').append(dot)});$('bins').replaceChildren();lab.bins.forEach((name,i)=>{const b=document.createElement('button');b.className='bin';b.dataset.bin=name;const key=document.createElement('small');key.textContent=`KEY ${i+1}`;b.append(key,document.createTextNode(name));b.onclick=()=>choose(name,b);$('bins').append(b)});$('message').textContent='Look closely, then choose a group.';$('explanation').textContent='Take your time. Each choice leads to a new discovery.';$('next').classList.add('hidden');$('card').focus({preventScroll:true})}
function choose(name,button){if(answered)return;answered=true;const row=deck[index],correct=name===row[2];if(correct)score++;else missed.push(row);document.querySelectorAll('.bin').forEach(b=>{b.disabled=true;if(b.dataset.bin===row[2])b.classList.add('correct')});if(!correct)button.classList.add('wrong');$('message').textContent=correct?'Good observation!':`A new discovery: ${row[2]}`;$('explanation').textContent=row[3];$('score').textContent=`★ ${score} correct`;$('next').textContent=index===deck.length-1?'Finish the lab →':'Next discovery →';$('next').classList.remove('hidden');$('next').focus({preventScroll:true})}
function finish(){$('play').classList.add('hidden');$('results').classList.remove('hidden');$('result-title').textContent=reviewing?'Practice complete!':`${lab.name} badge earned!`;$('result-text').textContent=`You sorted ${score} of ${deck.length} cards correctly. ${missed.length?'Practise the tricky cards again to help you remember.':'Ready for another discovery?'}`;$('review').classList.toggle('hidden',missed.length===0);if(!reviewing){try{const data=saved();data[lab.id]={complete:true,best:Math.max(Number(data[lab.id]?.best)||0,score)};localStorage.setItem('sprout-science-labs',JSON.stringify(data))}catch{}}$('results').scrollIntoView({block:'center'})}
$('next').onclick=()=>{if(!answered)return;index++;if(index<deck.length)show();else{answered=false;finish()}};$('back').onclick=home;$('map').onclick=home;$('again').onclick=()=>start(lab);$('review').onclick=()=>start(lab,[...missed]);document.addEventListener('keydown',e=>{if(!e.repeat&&!e.ctrlKey&&!e.metaKey&&!e.altKey&&!$('play').classList.contains('hidden')&&['1','2','3','4'].includes(e.key)){e.preventDefault();document.querySelectorAll('.bin')[Number(e.key)-1]?.click()}});home();
})();
