(() => {
'use strict';
const $=s=>document.querySelector(s),canvas=$('#track'),ctx=canvas.getContext('2d'),W=720,H=900,lanes=[228,360,492],playerY=704;
let mode='ready',lane=1,x=360,distance=0,coins=0,lives=3,nitro=100,boosting=false,boostLocked=false,speed=0,objects=[],spawn=0,shield=0,scroll=0,last=0,paint='#65efd3',sound=false,audio,best=0,bestCoins=0,storageOK=true;
try{const saved=JSON.parse(localStorage.getItem('sunset-sprint')||'{}');best=Math.max(0,Number(saved.best)||0);bestCoins=Math.max(0,Number(saved.coins)||0);if(['#65efd3','#ff738c','#ffd36c','#b49aff'].includes(saved.paint))paint=saved.paint}catch{storageOK=false}
function store(){try{localStorage.setItem('sunset-sprint',JSON.stringify({best,coins:bestCoins,paint}));storageOK=true}catch{storageOK=false}records()}
function records(){$('#best').textContent=Math.floor(best).toLocaleString();$('#best-coins').textContent=bestCoins;$('#best-note').textContent=!storageOK?'Storage unavailable. Records last for this visit.':best?'Your next run could be the one.':'Every great run starts at zero.'}records();
function beep(frequency,duration=.08){if(!sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=frequency;g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.start();o.stop(audio.currentTime+duration)}catch{}}
$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent=sound?'Sound on':'Sound off';$('#sound').setAttribute('aria-pressed',sound);beep(480)};
for(const b of $('#paints').children){b.setAttribute('aria-pressed',b.dataset.color===paint);b.onclick=()=>{paint=b.dataset.color;for(const p of $('#paints').children)p.setAttribute('aria-pressed',p===b);store()}}
function hud(){$('#distance').textContent=Math.floor(distance).toLocaleString();$('#coins').textContent=coins;$('#health').textContent='● '.repeat(lives)+'○ '.repeat(3-lives);$('#health').setAttribute('aria-label',lives+' lives');$('#speed').textContent=Math.round(speed*.4)+' KM/H';$('#nitro-value').textContent=Math.round(nitro)+'%';$('#nitro-fill').style.width=nitro+'%'}
function overlay(title,copy,button,tag){$('#overlay-title').textContent=title;$('#overlay-copy').textContent=copy;$('#start').textContent=button;$('#overlay-tag').textContent=tag;$('#overlay').hidden=false;$('#announcer').textContent=title+' '+copy}
function start(){lane=1;x=360;distance=0;coins=0;lives=3;nitro=100;boosting=false;boostLocked=false;speed=300;objects=[];spawn=.8;shield=0;scroll=0;mode='playing';$('#overlay').hidden=true;$('#pause').disabled=false;$('#pause').setAttribute('aria-label','Pause race');canvas.focus({preventScroll:true});if($('.game-frame').getBoundingClientRect().bottom>innerHeight)$('.game-frame').scrollIntoView({block:'start',behavior:'instant'});last=performance.now();hud();beep(660)}
function pause(){if(mode!=='playing')return;mode='paused';boosting=false;overlay('Take a breather.','Your race is paused. The road can wait.','Back to the road →','PIT STOP');$('#pause').setAttribute('aria-label','Resume race')}
function resume(){mode='playing';last=performance.now();$('#overlay').hidden=true;$('#pause').setAttribute('aria-label','Pause race');canvas.focus({preventScroll:true})}
function end(){mode='over';boosting=false;const record=distance>best;best=Math.max(best,Math.floor(distance));bestCoins=Math.max(bestCoins,coins);store();$('#pause').disabled=true;overlay(record?'A new personal best!':'What a ride.',`${Math.floor(distance).toLocaleString()} metres. ${coins} coins. Ready for another run?`,'Race again →',record?'THAT’S YOUR NEW RECORD':'BACK TO THE GARAGE');beep(130,.3)}
$('#start').onclick=()=>mode==='paused'?resume():start();$('#pause').onclick=()=>mode==='paused'?resume():pause();
function steer(direction){if(mode==='playing')lane=Math.max(0,Math.min(2,lane+direction))}
$('#left').onclick=()=>steer(-1);$('#right').onclick=()=>steer(1);
$('#boost').onpointerdown=e=>{if(mode!=='playing')return;e.preventDefault();boosting=true;e.currentTarget.setPointerCapture(e.pointerId)};for(const ev of ['pointerup','pointercancel','lostpointercapture'])$('#boost').addEventListener(ev,()=>boosting=false);
window.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select')||e.altKey||e.ctrlKey||e.metaKey)return;if(e.code==='KeyP'||e.code==='Escape'){if(e.repeat)return;if(mode==='playing'){e.preventDefault();pause()}else if(mode==='paused'){e.preventDefault();resume()}return}if(mode!=='playing')return;if(['ArrowLeft','ArrowRight','KeyA','KeyD','Space'].includes(e.code)){if(e.code==='Space'&&e.target.closest('button,a'))return;e.preventDefault();if(e.code==='Space')boosting=true;else if(!e.repeat)steer(['ArrowLeft','KeyA'].includes(e.code)?-1:1)}});
window.addEventListener('keyup',e=>{if(e.code==='Space')boosting=false});window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});
let swipe=null;canvas.addEventListener('pointerdown',e=>{swipe={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointerup',e=>{if(swipe&&Math.abs(e.clientX-swipe.x)>22&&Math.abs(e.clientX-swipe.x)>Math.abs(e.clientY-swipe.y))steer(e.clientX>swipe.x?1:-1);swipe=null});canvas.addEventListener('pointercancel',()=>swipe=null);
function roundRect(x,y,w,h,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function car(cx,cy,color,isPlayer=false){ctx.save();ctx.translate(cx,cy);ctx.shadowColor='#0008';ctx.shadowBlur=12;ctx.shadowOffsetY=7;roundRect(-39,-63,78,126,16,color);ctx.shadowBlur=0;ctx.shadowOffsetY=0;roundRect(-43,-38,9,29,3,'#10141f');roundRect(34,-38,9,29,3,'#10141f');roundRect(-43,25,9,28,3,'#10141f');roundRect(34,25,9,28,3,'#10141f');roundRect(-27,-28,54,48,9,'#192b3e');roundRect(-24,-24,48,14,4,'#b0e0ec99');roundRect(-24,36,48,15,4,'#1b2c3e');ctx.fillStyle='#ffffffaa';ctx.fillRect(-27,-53,14,6);ctx.fillRect(13,-53,14,6);ctx.fillStyle='#ff6479';ctx.fillRect(-27,54,12,5);ctx.fillRect(15,54,12,5);ctx.fillStyle='#ffffff21';ctx.fillRect(-3,-59,6,28);if(isPlayer&&boosting&&nitro>0&&!boostLocked&&mode==='playing'){ctx.fillStyle='#65efd3';ctx.beginPath();ctx.moveTo(-17,64);ctx.lineTo(-9,98+Math.random()*22);ctx.lineTo(0,64);ctx.fill();ctx.beginPath();ctx.moveTo(5,64);ctx.lineTo(13,98+Math.random()*22);ctx.lineTo(21,64);ctx.fill()}ctx.restore()}
function scene(){const sky=ctx.createLinearGradient(0,0,0,330);sky.addColorStop(0,'#282844');sky.addColorStop(.6,'#995c76');sky.addColorStop(1,'#ecaa86');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle='#ffd2a0';ctx.beginPath();ctx.arc(360,140,75,0,Math.PI*2);ctx.fill();ctx.fillStyle='#71475f';for(let i=0;i<5;i++)ctx.fillRect(281,157+i*12,158,3+i);ctx.fillStyle='#303249';ctx.beginPath();ctx.moveTo(0,270);ctx.lineTo(0,175);ctx.lineTo(75,233);ctx.lineTo(124,176);ctx.lineTo(220,267);ctx.lineTo(520,250);ctx.lineTo(616,160);ctx.lineTo(720,232);ctx.lineTo(720,320);ctx.fill();ctx.fillStyle='#1b2335';ctx.fillRect(0,275,W,625);
ctx.fillStyle='#22283a';for(let i=0;i<10;i++){const bx=i*79,bh=26+(i*41)%73;ctx.fillRect(bx,275-bh,49,bh);ctx.fillStyle='#ffbb8655';ctx.fillRect(bx+9,285-bh,4,4);ctx.fillRect(bx+23,298-bh,4,4);ctx.fillStyle='#22283a'}
ctx.fillStyle='#333a4b';ctx.fillRect(153,270,414,630);ctx.fillStyle='#252c3b';ctx.fillRect(165,270,390,630);ctx.fillStyle='#f6d49a';ctx.fillRect(159,270,4,630);ctx.fillRect(557,270,4,630);ctx.fillStyle='#8991a655';for(const lx of [294,426])for(let y=270+(scroll%110)-110;y<H;y+=110)ctx.fillRect(lx-2,Math.max(y,270),4,Math.max(0,Math.min(y+54,H)-Math.max(y,270)));
for(let i=0;i<6;i++){const y=280+(i*140+scroll*.65)%680;for(const side of [1,-1]){const px=side===1?93:627;ctx.fillStyle='#38445a';ctx.fillRect(px,y,4,65);ctx.strokeStyle='#344c59';ctx.lineWidth=5;for(const d of [-1,1]){ctx.beginPath();ctx.moveTo(px+2,y+8);ctx.quadraticCurveTo(px+d*35,y-28,px+d*43,y+5);ctx.stroke();ctx.beginPath();ctx.moveTo(px,y+6);ctx.quadraticCurveTo(px+d*20,y-40,px+d*27,y-25);ctx.stroke()}}}
ctx.fillStyle='#65efd31c';for(let i=0;i<12;i++)ctx.fillRect(119,290+(i*74+scroll)%620,7,22);
ctx.save();ctx.beginPath();ctx.rect(153,270,414,630);ctx.clip();for(const o of objects){if(o.type==='car')car(lanes[o.lane],o.y,o.color);else{ctx.save();ctx.translate(lanes[o.lane],o.y);ctx.shadowColor='#ffd36c';ctx.shadowBlur=17;ctx.fillStyle='#ffd36c';ctx.beginPath();ctx.arc(0,0,15,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#b88230';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#9a6b29';ctx.font='bold 19px Arial';ctx.textAlign='center';ctx.fillText('◇',0,7);ctx.restore()}}
ctx.restore();if(!shield||Math.floor(shield*9)%2===0)car(x,playerY,paint,true);if(shield>0){ctx.strokeStyle='#65efd388';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(x,playerY,56,83,0,0,Math.PI*2);ctx.stroke()}}
function update(dt){if(boostLocked&&nitro>=25)boostLocked=false;const boost=boosting&&!boostLocked&&nitro>0;nitro=Math.max(0,Math.min(100,nitro+(boost?-36:19)*dt));if(nitro===0)boostLocked=true;speed=300+Math.min(210,distance*.065)+(boost?170:0);distance+=speed*dt*.11;scroll+=speed*dt;shield=Math.max(0,shield-dt);x+=(lanes[lane]-x)*Math.min(1,dt*14);spawn-=dt;if(spawn<=0){const blocked=Math.floor(Math.random()*3);objects.push({type:'car',lane:blocked,y:200,color:['#dd7a90','#a693d6','#6ca3ba','#e5b978'][Math.floor(Math.random()*4)]});const coinLane=(blocked+1+Math.floor(Math.random()*2))%3;for(let i=0;i<3;i++)objects.push({type:'coin',lane:coinLane,y:150-i*55});spawn=1.45-Math.min(.3,distance/6000)}
for(const o of objects){o.y+=speed*dt;if(Math.abs(lanes[o.lane]-x)<(o.type==='car'?64:44)&&Math.abs(o.y-playerY)<(o.type==='car'?105:67)){if(o.type==='coin'){coins++;o.remove=true;beep(800+coins%5*90)}else if(shield<=0){lives--;shield=1.8;nitro=Math.max(0,nitro-20);o.remove=true;beep(90,.18);$('#announcer').textContent=`Bump! ${lives} lives remaining.`;if(lives===0){end();break}}}}objects=objects.filter(o=>!o.remove&&o.y<1020);hud()}
function frame(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;if(mode==='playing')update(dt);scene();requestAnimationFrame(frame)}hud();requestAnimationFrame(frame);
})();
